# -*- coding: utf-8 -*-
"""품질 업그레이드 Q1 — v2~v4 자리표 코스 실측 재작성 (1차 분량: 확정 8산).

사실 근거 (2026-09-19 세션 검증, 2소스 교차):
- 인왕산: 비짓서울 홍지문·탕춘대성 2km/1h20m × 한양도성 돈의문~창의문 4.0km/2h30m ×
  산악회 종주(사직공원~와룡공원) 4h10m. 성곽 구간 통제 변동 → 「이용 전 확인」.
- 가지산: 석남터널 왕복 6.0~7.3km/3h20~4h × 통도사 내원계곡 9km/5h × 종주 11km/6h30m.
- 화왕산(창녕): 928m 3대 진달래 군락 × 화왕산성·허준세트장. 자하곡 원점회귀 7~9.7km/5h ×
  옥천 제1등산로 왕복 ~10km/3-4h. (사이트 desc '영주' 오기 → 창녕 정정)
- 운장산(진안·완주): 운장대 1,126m. 피암목재 최단 왕복 ~5km/2~2.5h × 내처사 7.25km/3h53m ×
  독자동 능선 7.3km/5h55m. (desc '천황봉' 오기 → 운장대 정정)
- 비슬산(달성·청도): 천왕봉 1,083~1,084m. 유가사~천왕봉 ~2h × 유가사~월광봉~대견봉 3.3km 구간 ×
  완전 종주 4h30m.
- 영취산(여수): 정체성 정정 — 여수 진례봉 510m 진달래 명소(여수시 공식 코스 3종:
  GS칼텍스 후문 2.2km/70분 × 상암초교 1.8~2.3km/60~90분 × 종주 6.7km/2h30m).
  (사이트 '화순 1,090m 사자봉'은 부정확 — 여수 영취산으로 정정)
- 청량산(봉화·안동): 정체성 정정 — 의상봉 869.7m. 입석~청량사 1.3km/30~40분(원효대사 구도의 길) ×
  단축 4h × 봉화군 2코스 6.4km/5h × 종주 14.7km/6h. (사이트 '울산·경주 1,093m' 오기)
- 백암산(장성·순창): 정체성 정정 — 상왕봉 741.2m. 구암사 최단 5.1km/3h30m ×
  백양사 원점회귀(백학봉·도집봉·상왕봉·사자봉) ~3h × 전체 종주 10km/5h. (사이트 '화순 1,042m' 오기)
"""
import json as _json, pathlib as _pl

IC = 'assets/icons/icons.svg'
L = 'ko'


def pill(icon, label, value):
    return (f'<div class="stat-pill">\n<span class="pill-icon"><svg class="icon-svg"><use href="{IC}#icon-{icon}"></use></svg></span>\n'
            f'<span class="pill-label">{label}</span>\n<span class="pill-value">{value}</span>\n</div>')


def pill_meter(label, n, color):
    segs = ''.join(f'<span class="segment active-{color}"></span>' if i < n else '<span class="segment"></span>' for i in range(5))
    return (f'<div class="stat-pill">\n<span class="pill-icon"><svg class="icon-svg"><use href="{IC}#icon-star"></use></svg></span>\n'
            f'<span class="pill-label">{label}</span>\n'
            f'<div aria-label="난이도: {n}단계" class="difficulty-meter"><div class="meter-segments">{segs}</div></div>\n</div>')


def seg(no, title, km, time, body, bar, kind, tip_text):
    tip = (f'<div class="{kind}"><svg class="icon-svg"><use href="{IC}#icon-{"warning" if kind=="warn" else "tip"}"></use></svg> {tip_text}</div>')
    return (f'<div class="seg"><div class="seg-head"><div class="seg-no">{no}</div><div><div class="seg-title">{title}</div>'
            f'<div class="acc-meta-chips"><span class="meta-chip"><svg class="icon-svg"><use href="{IC}#icon-ruler"></use></svg> {km}</span>'
            f'<span class="meta-chip"><svg class="icon-svg"><use href="{IC}#icon-clock"></use></svg> {time}</span></div></div><div class="seg-arrow">⌄</div></div>'
            f'<div class="seg-body"><p>{body}</p><div class="bar"><div class="fill" style="width:{bar}%"></div></div>{tip}</div></div>')


def tipcard(icon, title, items):
    lis = ''.join(f'<li>{x}</li>' for x in items)
    return f'<div class="card tipcard"><h2><svg class="icon-svg"><use href="{IC}#icon-{icon}"></use></svg> {title}</h2><ul>{lis}</ul></div>'


def cp(n, name, badge, badge_cls, alt, km, amen):
    return (f'<div class="timeline-item{" start" if n==1 else ""}">\n<div class="timeline-marker">{n}</div>\n<div class="timeline-content">\n'
            f'<div class="timeline-header">\n<span class="checkpoint-name">{name}</span>\n<span class="badge {badge_cls}">{badge}</span>\n</div>\n'
            f'<div class="timeline-meta">\n<span class="meta-item"><svg class="icon-svg"><use href="{IC}#icon-mountain"></use></svg> {alt}</span>\n'
            f'<span class="meta-item"><svg class="icon-svg"><use href="{IC}#icon-ruler"></use></svg> {km}</span>\n</div>\n'
            f'<div class="timeline-features">\n<span class="feature-label">{"Amenities" if L=="en" else "편의시설"}:</span> {amen}\n      </div>\n</div>\n</div>')


def elev_svg(gid, color, label, path_pts, peak_xy):
    (px, py) = peak_xy
    return (f'<svg viewbox="0 0 760 220"><defs><lineargradient id="{gid}" x1="0" x2="0" y1="0" y2="1">'
            f'<stop offset="0%" stop-color="{color}" stop-opacity=".34"></stop><stop offset="100%" stop-color="{color}" stop-opacity=".05"></stop></lineargradient></defs>'
            f'<path d="{path_pts} L740 210 L20 210 Z" fill="url(#{gid})"></path><path d="{path_pts}" fill="none" stroke="{color}" stroke-linecap="round" stroke-width="4"></path>'
            f'<circle cx="{px}" cy="{py}" fill="{color}" r="6"></circle><text fill="{color}" font-size="12" x="{px-150}" y="{py-10}">{label}</text></svg>')


def map_svg(color, note, s_label, e_label, path, nodes):
    ns = ''.join(f'<circle cx="{cx}" cy="{cy}" fill="{color}" r="{r}"></circle>' for cx, cy, r in nodes)
    return (f'<svg viewbox="0 0 760 420"><rect fill="var(--surface2)" height="400" rx="22" width="740" x="10" y="10"></rect>'
            f'<path d="{path}" fill="none" stroke="{color}" stroke-linecap="round" stroke-width="6"></path>{ns}'
            f'<text font-size="12" x="{nodes[0][0]-60}" y="{nodes[0][1]+28}">{s_label}</text>'
            f'<text font-size="12" x="{nodes[-1][0]-160}" y="{nodes[-1][1]-18}">{e_label}</text>'
            f'<text fill="var(--muted)" font-size="12" x="34" y="44">{note}</text></svg>')


def panels(courses):
    out = []
    for i, c in enumerate(courses):
        active = ' active' if i == 0 else ''
        flow = '<span class="arr">→</span>'.join(f'<span class="chip">{x}</span>' for x in c['flow'])
        segs = ''.join(seg(*s) for s in c['segs'])
        tips = ''.join(tipcard(*t) for t in c['tips'])
        cps = ''.join(cp(n + 1, *x) for n, x in enumerate(c['cps']))
        out.append(f'''<section class="panel {c['color']}{active}" id="{c['id']}"><div class="panel-top"><span class="level"><svg class="icon-svg"><use href="{IC}#icon-season"></use></svg> {c['level']}</span><div><div class="panel-name">{c['name']}</div><div class="panel-sub">{c['sub']}</div></div></div><div class="tabs"><button class="tab active" data-tab="overview"><svg class="icon-svg"><use href="{IC}#icon-prep"></use></svg> {c['tabs'][0]}</button><button class="tab" data-tab="route"><svg class="icon-svg"><use href="{IC}#icon-book"></use></svg> {c['tabs'][1]}</button><button class="tab" data-tab="map"><svg class="icon-svg"><use href="{IC}#icon-location"></use></svg> {c['tabs'][2]}</button><button class="tab" data-tab="tips"><svg class="icon-svg"><use href="{IC}#icon-tip"></use></svg> {c['tabs'][3]}</button></div>
<div class="playbook-split-container"><div class="playbook-main-col"><div class="tabpane active" data-pane="overview"><div class="course-stats-summary">
{c['pills']}
</div><div class="section-title"><h2>{c['h_flow']}</h2><div class="line"></div></div><div class="card"><div class="flow">{flow}</div></div><div class="section-title"><h2>{c['h_elev']}</h2><div class="line"></div></div><div class="card elev">{elev_svg('g' + c['id'] + c['color'][:2], c['hex'], c['elev_label'], c['elev_path'], c['elev_peak'])}</div><p class="desc">{c['desc']}</p></div><div class="tabpane" data-pane="route"><div class="section-title"><h2>{c['h_route']}</h2><div class="line"></div></div><div class="segments">{segs}</div></div><div class="tabpane" data-pane="tips"><div class="tips-grid">{tips}</div></div></div><div class="playbook-sidebar-col"><div class="tabpane" data-pane="map"><div class="section-title"><h2>{c['h_map']}</h2><div class="line"></div></div><div class="card map">{map_svg(c['hex'], c['map_note'], c['map_start'], c['map_end'], c['map_path'], c['map_nodes'])}</div><div class="section-title"><h2>{c['h_cp']}</h2><div class="line"></div></div><div class="checkpoint-timeline">
{cps}
</div></div></div></div>
</section>''')
    return '\n'.join(out)


# 코스 헬퍼: (id,color,hex,meter,level), name(2), dist(2), time(2), flow, desc(2), segs[4], cps, tips[3], elev, map
C = dict


def mk_segs(items, ko):
    out = []
    for (no, t, km, tm, b, bar, kind, tip) in items:
        out.append((no, t[0 if ko else 1], km, tm, b[0 if ko else 1], bar, kind, tip[0 if ko else 1]))
    return out


def mk_cps(items, ko):
    return [(nm[0 if ko else 1], bd[0 if ko else 1], cls, alt, km, am[0 if ko else 1]) for (nm, bd, cls, alt, km, am) in items]


def mk_tips(items, ko):
    return [(ic, t[0 if ko else 1], [x[0 if ko else 1] for x in lst]) for (ic, t, lst) in items]


F7 = {}

F7.update({
 # ── 인왕산 (v2) — 100대 목록 외(산림 명산) ──
 'inwangsan': dict(ko_name='인왕산', en_name='Inwangsan', alt='338m', b100=False,
  intro_ko='서울 도심과 맞닿은 338m의 성곽 산. 한양도성 인왕구간이 능선을 따라 이어지고 정상에서 서울 전경이 열립니다.',
  intro_en='A 338 m fortress mountain touching downtown Seoul — the Hanyangdoseong city wall runs its ridge, with the whole city opening from the top.',
  permit=('불필요', 'N/A'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('홍지문~탕춘대성 길','Hongjimun–Tangchundaeseong Trail'),
     dist=('약 2km','~2 km'), time=('약 1시간 20분','~1 h 20 m'),
     flow=('홍지문','탕춘대성','인왕산 능선'),
     desc=('비짓서울이 안내하는 대표 산책 코스. 홍지문에서 탕춘대성 길을 지나 능선에 오르는 짧고 명확한 구간이다.',
          'The official VisitSeoul walk: a short, clear line from Hongjimun up the Tangchundaeseong path to the ridge.'),
     segs=[(1,('홍지문 출발','From Hongjimun'),'0.5km','15분',
            ('홍지문 앞에서 시작해 숲길로 접어든다. 금천구약터 방면 안내판이 있다.','The walk starts at Hongjimun into forest, signposted toward the old spring site.'),20,'tip',
            ('지하철 3호선 무악재역 하차 후 도보 접근이 일반적이다.','Gyeongbokgong Station line 3 then a short walk — check the route before you go.')),
           (2,('탕춘대성 길','Tangchundaeseong path'),'1km','40~50분',
            ('가파른 오르막이 있는 성길. 겨울철엔 결빙 주의가 필요하다.','A steep fortified path — watch for ice in winter.'),60,'warn',
            ('우천 직후·결빙 시 아이젠이 권장된다.','Crampons are recommended when icy.')),
           (3,('인왕산 능선','Inwangsan ridge'),'0.5km','15~20분',
            ('능선에 오르면 서울 도심 전경이 열린다. 한양도성 성곽길과 만난다.','The ridge opens the city panorama and meets the city-wall trail.'),90,'tip',
            ('성곽 구간 통제 여부는 방문 전 확인한다.','Check whether the wall section is open before visiting.'))],
     cps=[(('홍지문','Hongjimun'),('출발','Trailhead'),'badge-trailhead','해발 약 60m','0km',('주차 협소·지하철 접근','Limited parking; subway access')),
          (('탕춘대성','Tangchundaeseong'),('경유','Waypoint'),'badge-landmark','해발 약 200m','0.5km',('없음','None')),
          (('인왕산 능선','Ridge'),('경유','Waypoint'),'badge-shelter','해발 약 300m','2km',('전망','Viewpoint'))],
     tips=[('backpack',('준비물','Gear'),('운동화·물. 짧은 산책 수준.','Sneakers and water — a short walk.')),
           ('book',('입산','Entry'),('별도 예약 불필요 — 성곽 구간 개방 여부만 확인.','No reservation; just check wall-section openings.')),
           ('shield',('주의','Cautions'),('탕춘대성 급경사 구간 결빙 주의.','Steep path ices over in winter.'))],
     elev='M20 195 C200 175, 420 120, 600 90 S710 70, 740 66', peak=(740,66), elabel='약 338m',
     mnote='홍지문 코스', mstart='홍지문', mend='능선',
     mpath='M110 350 C260 320, 400 250, 520 180 S680 90, 710 70', mnodes=[(110,350,10),(520,180,8),(710,70,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('한양도성 인왕구간 종주','Hanyangdoseong Inwang Section'),
     dist=('4.0km','4.0 km'), time=('약 2시간 30분','~2.5 h'),
     flow=('돈의문터','인왕산 정상','윤동주 시인의 언덕','창의문'),
     desc=('서울시 공식 한양도성 인왕구간 — 돈의문터에서 창의문까지 4.0km·약 2시간 30분. 정상 338m를 넘는 도심 성곽 종주다.',
          'The official Seoul City Wall Inwang section: 4.0 km and about 2.5 hours from Donuimun site to Changuimun over the 338 m summit.'),
     segs=[(1,('돈의문터 → 인왕산','Donuimun → summit'),'1.5km','1시간',
            ('성곽을 따라 오르면 인왕산 정상 338m. 서울 전경 조망의 핵심이다.','Along the wall to the 338 m summit — the heart of the city panorama.'),55,'tip',
            ('정상 통제 시 우회 안내를 따른다.','Follow detour notices if the summit is closed.')),
           (2,('정상 → 윤동주 시인의 언덕','Summit → Yun Dong-ju hill'),'1.5km','50분',
            ('능선 성곽길을 따라 내려가 문학의 언덕에 닿는다.','Down the wall ridge to the poet\'s hill.'),80,'warn',
            ('성곽 보호 구간 — 벽에 기대거나 담장을 넘지 않는다.','Protected wall — never lean on or climb it.')),
           (3,('윤동주 언덕 → 창의문','Poet\'s hill → Changuimun'),'1km','40분',
            ('부암동 주택가 사이 성곽길로 마무리한다.','The wall descends through Buam-don streets to finish.'),100,'tip',
            ('창의문에서 버스·택시 환승이 가능하다.','Buses and taxis connect at Changuimun.'))],
     cps=[(('돈의문터','Donuimun site'),('출발','Trailhead'),'badge-trailhead','해발 약 40m','0km',('광화문 인근','Near Gwanghwamun')),
          (('인왕산','Inwangsan'),('정상','Summit'),'badge-summit','338m','1.5km',('서울 전망','City panorama')),
          (('윤동주 시인의 언덕','Yun Dong-ju hill'),('경유','Waypoint'),'badge-landmark','해발 약 150m','3km',('기념 공간','Memorial spot')),
          (('창의문','Changuimun'),('도착','Finish'),'badge-trailhead','해발 약 80m','4km',('버스 정류장','Bus stop'))],
     tips=[('backpack',('준비물','Gear'),('등산화·물 0.5L. 도심 산행이다.','Walking shoes, half a liter of water — an urban hike.')),
           ('book',('입산','Entry'),('무료 — 성곽 개방 시간은 공식 안내 확인.','Free; check official wall opening hours.')),
           ('shield',('주의','Cautions'),('주말 혼잡·야간 통제 구간이 있다.','Weekend crowds; some sections close at night.'))],
     elev='M20 190 C120 165, 260 105, 420 85 S640 120, 740 150', peak=(420,85), elabel='338m',
     mnote='한양도성 인왕구간', mstart='돈의문터', mend='창의문',
     mpath='M120 320 C260 280, 400 160, 520 110 S680 130, 700 160', mnodes=[(120,320,10),(520,110,12),(700,160,10)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('사직공원~인왕산~와룡공원 능선 종주','Sajik–Inwangsan–Waryong Traverse'),
     dist=('약 9km','~9 km'), time=('약 4시간','~4 h'),
     flow=('사직공원','전망대','인왕산 정상','창의문','숙정문','와룡공원'),
     desc=('산악회 기준 약 4시간 10분의 인왕산 능선 완주. 사직공원에서 전망대·정상을 거쳐 창의문·숙정문·말바위를 지나 와룡공원으로 빠진다.',
          'The full Inwangsan ridge in about 4 hours: Sajik Park past the lookout and summit, over Changuimun, Sukjeongmun and Malbawi to Waryong Park.'),
     segs=[(1,('사직공원 → 전망대','Sajik → lookout'),'2km','50분',
            ('사직터널 위 능선으로 오른다. 무악재 방면 조망이 열린다.','Up the ridge above Sajik Tunnel with views toward Mokgye Pass.'),30,'tip',
            ('사직공원 주차는 협소하다 — 대중교통 권장.','Sajik parking is tight — use transit.')),
           (2,('전망대 → 인왕산 → 창의문','Lookout → summit → Changuimun'),'3km','1시간 20분',
            ('능선 오르내림 후 정상 338m와 성곽 구간을 지난다.','Rolling ridge to the 338 m summit and along the wall.'),65,'warn',
            ('성곽 구간 혼잡 — 한 줄로 통행한다.','Single file on the wall sections.')),
           (3,('창의문 → 숙정문 → 말바위','Changuimun → Sukjeongmun → Malbawi'),'2.5km','1시간',
            ('북한산 방면 능선을 타고 말바위 전망에 닿는다.','The ridge continues toward Bukhansan to the Malbawi viewpoint.'),85,'tip',
            ('말바위는 바위 노출 — 우천 시 미끄럽다.','Malbawi rock is slippery when wet.')),
           (4,('말바위 → 와룡공원 하산','Malbawi → descent'),'1.5km','50분',
            ('성신여대 방면 와룡공원으로 하산한다.','Descend to Waryong Park near Sungshin Women\'s University.'),100,'tip',
            ('와룡공원에서 4호선 성신여대입구역으로 환승.','Subway line 4 connects at Sungshin Women\'s Univ. Station.'))],
     cps=[(('사직공원','Sajik Park'),('출발','Trailhead'),'badge-trailhead','해발 약 60m','0km',('주차·화장실','Parking, restrooms')),
          (('인왕산','Inwangsan'),('정상','Summit'),'badge-summit','338m','3.5km',('서울 전망','Panorama')),
          (('숙정문','Sukjeongmun'),('경유','Waypoint'),'badge-landmark','해발 약 200m','6km',('성문','Gate')),
          (('말바위','Malbawi'),('경유','Waypoint'),'badge-landmark','해발 약 280m','7.5km',('바위 전망','Rock viewpoint')),
          (('와룡공원','Waryong Park'),('도착','Finish'),'badge-trailhead','해발 약 80m','9km',('지하철 접근','Subway access'))],
     tips=[('backpack',('준비물','Gear'),('등산화·물 1L — 도심 장거리 능선.','Boots, 1 L water — a long urban ridge.')),
           ('book',('입산','Entry'),('무료·예약 불필요.','Free, no reservation.')),
           ('shield',('주의','Cautions'),('일부 성곽·능선 구간이 통제될 수 있다 — 공지 확인.','Some wall and ridge sections may close; check notices.'))],
     elev='M20 190 C140 155, 280 95, 430 80 S600 95, 700 70 S730 110, 740 140', peak=(700,70), elabel='338m',
     mnote='인왕산 능선 종주', mstart='사직공원', mend='와룡공원',
     mpath='M120 340 C250 300, 380 190, 500 140 S660 80, 700 90 S640 240, 480 290 S240 340, 120 340', mnodes=[(120,340,10),(500,140,8),(700,90,12),(120,340,10)]),
  ]),
 # ── 가지산 (v2) ──
 'gajisan': dict(ko_name='가지산', en_name='Gajisan', alt='1,240m', b100=True,
  intro_ko='영남알프스 최고봉 1,240m. 통도사 권역의 석남터널 최단 코스와 내원계곡의 깊은 숲이 유명합니다.',
  intro_en='The highest of the Yeongnam Alps at 1,240 m — famous for the quick Seoknam Tunnel route and the deep forests of Naewon Valley near Tongdosa.',
  permit=('불필요', 'N/A'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('석남터널~중봉~가지산 왕복','Seoknam Tunnel–Jungbong Round Trip'),
     dist=('약 6.5km','~6.5 km'), time=('3시간 30분~4시간','3.5–4 h'),
     flow=('석남터널 주차장','중봉','가지산 1,240m'),
     desc=('울산 쪽 최단·대표 코스. 석남터널 주차장에서 중봉을 거쳐 정상까지 왕복 — 실측 기록 6.5km·3시간 34분.',
          'The classic short route from the Ulsan side: up through Jungbong to the summit and back — 6.5 km and 3h34m by tracked logs.'),
     segs=[(1,('석남터널 → 중봉','Tunnel → Jungbong'),'1.8km','50~60분',
            ('완만한 임도·숲길로 시작해 중봉 삼거리에 닿는다.','A gentle forest-road start to the Jungbong junction.'),35,'tip',
            ('주차장은 이른 아침 확보를 권한다.','Arrive early for parking.')),
           (2,('중봉 → 가지산 정상','Jungbong → summit'),'1.5km','50~60분',
            ('능선 오름이 본격화된다. 정상 1,240m에서 영남알프스 능선이 열린다.','The ridge climb proper tops out at 1,240 m over the Yeongnam Alps.'),75,'warn',
            ('바위 구간은 우천 시 미끄럽다.','Rock pitches are slick in rain.')),
           (3,('정상 → 하산','Summit → descent'),'3.2km','1시간 40분',
            ('온 길을 되돌아 석남터널로 내려온다.','Retrace to the tunnel trailhead.'),100,'tip',
            ('신불산 방면 능선 조망을 마지막으로 즐긴다.','Take a last look toward the Sinbulsan ridge.'))],
     cps=[(('석남터널 주차장','Seoknam Tunnel lot'),('출발','Trailhead'),'badge-trailhead','해발 약 650m','0km',('주차장','Parking')),
          (('중봉','Jungbong'),('경유','Waypoint'),'badge-landmark','해발 약 1,100m','1.8km',('삼거리','Junction')),
          (('가지산','Gajisan'),('정상','Summit'),'badge-summit','1,240m','3.3km',('영남알프스 조망','Alps panorama'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1L·방풍.','Boots, 1 L water, wind shell.')),
           ('book',('입산','Entry'),('별도 예약·허가 불필요.','No reservation or permit needed.')),
           ('shield',('주의','Cautions'),('가을 억새철·주말 혼잡.','Crowded on autumn weekends.'))],
     elev='M20 175 C180 155, 330 110, 480 80 S660 48, 740 42', peak=(740,42), elabel='1,240m',
     mnote='석남터널 코스', mstart='석남터널', mend='가지산',
     mpath='M110 335 C240 315, 350 265, 460 210 S620 95, 695 55', mnodes=[(110,335,10),(460,210,8),(695,55,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('내원계곡~가지산 등반','Naewon Valley Ascent'),
     dist=('약 9km','~9 km'), time=('약 5시간','~5 h'),
     flow=('통도사 내원계곡','석남사 계곡','가지산 1,240m'),
     desc=('양산 통도사 쪽 등반로 — 내원계곡을 오르며 석남사·석남사계곡을 거쳐 정상에 오르는 약 9km·5시간 코스.',
          'The Yangsan side: about 9 km and five hours up Naewon Valley past Seoknamsa temple and its gorge to the summit.'),
     segs=[(1,('내원계곡 입구 → 계곡길','Valley mouth → gorge'),'3km','1시간 20분',
            ('통도사 권역 깊은 계곡숲을 따라 오른다.','A long climb through the deep valley forest of the Tongdosa area.'),30,'tip',
            ('계곡수가 맑다 — 여름 산행의 백미.','Clear streams make this a summer favorite.')),
           (2,('석남사 → 능선','Seoknamsa → ridge'),'3km','1시간 40분',
            ('석남사 계곡 탐방 후 가파른 오름으로 주능선에 붙는다.','Past the temple gorge, a steep pitch gains the main ridge.'),65,'warn',
            ('고도 차가 크다 — 체력 배분 필요.','Big elevation gain — pace yourself.')),
           (3,('능선 → 가지산 정상','Ridge → summit'),'1.5km','50분',
            ('주능선을 따라 정상 완등 후 내원계곡으로 하산한다.','Follow the ridge to the top, then descend the valley.'),90,'tip',
            ('하산은 온 계곡길 역주행.','Descend by the same valley route.'))],
     cps=[(('내원계곡 입구','Naewon Valley mouth'),('출발','Trailhead'),'badge-trailhead','해발 약 400m','0km',('주차·식수','Parking')),
          (('석남사','Seoknamsa'),('경유','Waypoint'),'badge-landmark','해발 약 700m','4km',('사찰·계곡','Temple, gorge')),
          (('가지산','Gajisan'),('정상','Summit'),'badge-summit','1,240m','7.5km',('조망','Panorama'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1.5L·점심.','Boots, 1.5 L water, lunch.')),
           ('book',('입산','Entry'),('통도사 권역 — 주차 요금 체계는 이용 전 확인.','Tongdosa area — check parking fees before you go.')),
           ('shield',('주의','Cautions'),('여름 계곡물 불기 — 우천 후 급류 위험.','Never enter the streams after rain — flash floods.'))],
     elev='M20 195 C170 175, 320 125, 470 90 S650 50, 740 44', peak=(740,44), elabel='1,240m',
     mnote='내원계곡 코스', mstart='내원계곡', mend='가지산',
     mpath='M110 350 C240 325, 350 275, 460 220 S620 100, 690 60', mnodes=[(110,350,10),(460,220,8),(690,60,12)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('석남터널~비룡폭포~쌍폭포 종주','Seoknam–Biryeong Falls–Ssangpok Traverse'),
     dist=('약 11km','~11 km'), time=('약 6시간 30분','~6.5 h'),
     flow=('석남터널','가지산 1,240m','비룡폭포','쌍폭포','하산'),
     desc=('가지산 대표 종주 — 정상 완등 후 비룡폭포·쌍폭포 계곡을 잇는 약 11km·6시간 30분 코스.',
          'The signature traverse: summit first, then down past Biryeong and Ssangpok waterfalls — about 11 km and 6.5 hours.'),
     segs=[(1,('석남터널 → 가지산','Tunnel → summit'),'3.3km','1시간 50분',
            ('최단 코스로 먼저 정상을 밟는다.','Tag the summit first via the short route.'),45,'tip',
            ('종주 거리 감안 이른 출발.','Start early for the full day.')),
           (2,('정상 → 비룡폭포','Summit → Biryeong Falls'),'3.5km','1시간 40분',
            ('북서 능선을 내려가 폭포 계곡에 진입한다.','Down the northwest ridge into the waterfall gorge.'),70,'warn',
            ('하산 급경사 — 지팡이 권장.','Steep descent — poles recommended.')),
           (3,('비룡폭포 → 쌍폭포','Biryeong → Ssangpok'),'2.5km','1시간 20분',
            ('계곡 폭포 2련을 잇는 하산로. 물소리와 함께 내려온다.','The double-waterfall descent runs with water sound all the way.'),90,'tip',
            ('폭포 주변 바위 접근 금지.','Keep off wet rocks at the falls.')),
           (4,('쌍폭포 → 하산 완료','Ssangpok → exit'),'1.7km','1시간',
            ('계곡 끝 들머리로 빠져 나와 복귀 동선을 잡는다.','Exit at the valley trailhead and arrange transport.'),100,'warn',
            ('원점회귀가 아니므로 귀가 계획을 미리 세운다.','Point-to-point — plan the return in advance.'))],
     cps=[(('석남터널 주차장','Tunnel lot'),('출발','Trailhead'),'badge-trailhead','해발 약 650m','0km',('주차장','Parking')),
          (('가지산','Gajisan'),('정상','Summit'),'badge-summit','1,240m','3.3km',('조망','Panorama')),
          (('비룡폭포','Biryeong Falls'),('경유','Waypoint'),'badge-landmark','해발 약 600m','6.8km',('폭포','Waterfall')),
          (('쌍폭포','Ssangpok Falls'),('도착','Finish'),'badge-trailhead','해발 약 400m','약 11km',('계곡 들머리','Valley trailhead'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 2L·점심·헤드램프.','Boots, 2 L water, lunch, headlamp.')),
           ('book',('입산','Entry'),('별도 예약 불필요.','No reservation needed.')),
           ('shield',('주의','Cautions'),('우천 시 폭포 계곡 수위 상승 — 대체 동선 준비.','Gorge water rises in rain — have a fallback route.'))],
     elev='M20 165 C150 145, 280 95, 420 70 S560 95, 660 130 S710 165, 740 175', peak=(420,70), elabel='1,240m',
     mnote='가지산 종주', mstart='석남터널', mend='쌍폭포',
     mpath='M120 90 C240 120, 340 170, 460 220 S620 310, 680 340', mnodes=[(120,90,10),(460,220,8),(680,340,12)]),
  ]),
 # ── 화왕산 (v2, desc 정정: 창녕) ──
 'hwawangsan': dict(ko_name='화왕산', en_name='Hwawangsan', alt='928m', b100=True,
  intro_ko='경남 창녕의 진달래 명산 928m. 3대 진달래 군락지로 봄이면 능선 전체가 붉게 물들며, 백제 화왕산성과 허준 세트장이 함께합니다.',
  intro_en='Changnyeong\'s azalea mountain at 928 m — one of Korea\'s three great azalea colonies, with a Baekje mountain fortress and the Heo Jun drama set on top.',
  permit=('불필요', 'N/A'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('옥천 제1등산로 왕복','Okcheon Trail No.1 Round Trip'),
     dist=('약 10km','~10 km'), time=('3~4시간','3–4 h'),
     flow=('옥천 매표소','임도','화왕산성','정상'),
     desc=('완만한 임도 중심의 기본 코스. 옥천 매표소에서 임도를 따라 산성과 정상으로 오르는 왕복 약 10km 코스다.',
          'The base route on gentle forest roads: about 10 km round trip from the Okcheon gate past the fortress to the summit.'),
     segs=[(1,('옥천 매표소 → 임도','Okcheon gate → forest road'),'3km','1시간',
            ('완만한 임도가 이어져 남녀노소 접근이 쉽다.','A gentle road suitable for all ages.'),25,'tip',
            ('매표소 주차·화장실 이용 가능.','Parking and restrooms at the gate.')),
           (2,('임도 → 화왕산성','Road → fortress'),'1.5km','40분',
            ('백제 축조 화왕산성 터를 지나 능선에 붙는다.','Past the Baekje fortress works to the ridge.'),55,'tip',
            ('진달래철에는 이 구간부터 붉은 능선이 시작된다.','In season the red ridge begins here.')),
           (3,('산성 → 정상 → 하산','Fortress → summit → down'),'5.5km','1시간 40분',
            ('정상 928m 오름 후 온 길로 하산한다.','Climb to 928 m and return the same way.'),100,'warn',
            ('4월 진달래 절정기 주말 혼잡 — 이른 아침.','Peak azalea weekends are packed — go early.'))],
     cps=[(('옥천 매표소','Okcheon gate'),('출발','Trailhead'),'badge-trailhead','해발 약 150m','0km',('주차·화장실','Parking, restrooms')),
          (('화왕산성','Hwawang fortress'),('경유','Waypoint'),'badge-landmark','해발 약 700m','4.5km',('유적','Ruins')),
          (('화왕산','Hwawangsan'),('정상','Summit'),'badge-summit','928m','5km',('진달래·조망','Azaleas, views'))],
     tips=[('backpack',('준비물','Gear'),('가벼운 등산화·물 1L.','Light boots, 1 L water.')),
           ('book',('입산','Entry'),('별도 예약 불필요 — 매표소 운영 여부는 이용 전 확인.','No reservation; check gate operations.')),
           ('shield',('주의','Cautions'),('봄철 진달래 함부로 꺾지 않기.','Never pick the azaleas.'))],
     elev='M20 195 C170 180, 320 140, 470 105 S650 60, 740 50', peak=(740,50), elabel='928m',
     mnote='옥천 코스', mstart='옥천 매표소', mend='정상',
     mpath='M110 345 C240 320, 350 270, 460 215 S620 100, 690 60', mnodes=[(110,345,10),(460,215,8),(690,60,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('자하곡 원점회귀','Jahagok Circuit'),
     dist=('약 7~9.7km','7–9.7 km'), time=('약 5시간','~5 h'),
     flow=('자하곡 주차장','화왕산성','허준 세트장','진달래 군락지','정상','도성암'),
     desc=('인기 원점회귀 코스 — 자하곡주차장에서 산성·허준 세트장·진달래 군락지를 거쳐 정상, 제3등산로·도성암으로 되돌아온다.',
          'The popular loop: from the Jahagok lot past the fortress, Heo Jun set and azalea colonies to the summit, returning past Dogseongam hermitage.'),
     segs=[(1,('자하곡 → 화왕산성 → 세트장','Jahagok → fortress → set'),'2.5km','1시간',
            ('계곡길로 올라 산성과 드라마 세트장을 둘러본다.','Up the valley to the fortress and drama-set sights.'),30,'tip',
            ('세트장은 촬영 중 비공개일 수 있다.','The set may close during filming.')),
           (2,('세트장 → 진달래 군락지 → 정상','Set → azaleas → summit'),'2km','1시간 20분',
            ('능선 진달래 군락을 지나 정상 928m에 오른다.','Through the ridge azaleas to the 928 m summit.'),65,'warn',
            ('군락지 데크·탐방로 이탈 금지.','Stay on the boardwalks through the colonies.')),
           (3,('정상 → 제3등산로 → 도성암','Summit → Trail 3 → Dogseongam'),'2.5km','1시간 10분',
            ('소나무 숲길로 내려와 도성암을 지난다.','Descend through pine forest past Dogseongam.'),85,'tip',
            ('도성암~정상 1.6km는 소나무 숲길이다.','The last 1.6 km to the temple is a pine path.')),
           (4,('도성암 → 자하곡 복귀','Dogseongam → return'),'2~2.7km','50~70분',
            ('주차장으로 원점 회귀한다.','Back to the lot to close the loop.'),100,'tip',
            ('봄철 셔틀·임시 주차 운영 여부는 군 안내 확인.','Check county notices for spring shuttles.'))],
     cps=[(('자하곡 주차장','Jahagok lot'),('출발','Trailhead'),'badge-trailhead','해발 약 200m','0km',('주차·화장실','Parking, restrooms')),
          (('허준 세트장','Heo Jun set'),('경유','Waypoint'),'badge-landmark','해발 약 550m','2.5km',('촬영지','Film set')),
          (('진달래 군락지','Azalea colony'),('경유','Waypoint'),'badge-landmark','해발 약 800m','3.5km',('군락','Colony')),
          (('화왕산','Hwawangsan'),('정상','Summit'),'badge-summit','928m','4.5km',('조망','Views')),
          (('도성암','Dogseongam'),('경유','Waypoint'),'badge-shelter','해발 약 400m','7km',('암자','Hermitage'))],
     tips=[('backpack',('준비물','Gear'),('등산화·물 1L·봄 자외선 대비.','Boots, 1 L water, spring sun protection.')),
           ('book',('입산','Entry'),('별도 예약 불필요.','No reservation needed.')),
           ('shield',('주의','Cautions'),('진달래 절정(4월 초~중순) 혼잡 — 평일 권장.','Peak bloom (early–mid April) is crowded — weekdays are best.'))],
     elev='M20 190 C160 170, 310 125, 460 90 S640 55, 730 48 S740 100, 740 130', peak=(730,48), elabel='928m',
     mnote='자하곡 순환', mstart='자하곡', mend='자하곡',
     mpath='M120 330 C250 300, 360 240, 480 190 S640 90, 690 70 S610 240, 450 285 S230 330, 120 330', mnodes=[(120,330,10),(480,190,8),(690,70,12),(120,330,10)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('화왕산 능선 완주','Full Ridge Traverse'),
     dist=('약 9km','~9 km'), time=('약 6시간','~6 h'),
     flow=('자하곡','정상 928m','능선 완주','옥천'),
     desc=('실측 진달래 산행 기록 기준 능선 완주 약 9km·6시간대. 진달래 능선 전체를 종주하는 화왕산의 완전 코스.',
          'The whole azalea ridge end to end — about 9 km and six hours per tracked spring logs.'),
     segs=[(1,('자하곡 → 정상','Jahagok → summit'),'4.5km','2시간',
            ('군락지·산성을 지나 정상까지 오른다.','Up past the colonies and fortress to the summit.'),45,'tip',
            ('일출~이른 아침 출발로 진달래 순번을 피한다.','Start at dawn to beat the bloom crowds.')),
           (2,('정상 → 능선 완주','Summit → full ridge'),'3km','2시간',
            ('능선 전체를 따라 진달래 군락이 이어지는 종주.','The ridge run through continuous azalea colonies.'),75,'warn',
            ('완만해 보이지만 거리가 길다 — 수분 보충.','Looks gentle but runs long — hydrate.')),
           (3,('능선 → 옥천 하산','Ridge → Okcheon descent'),'1.5km','1시간',
            ('제1등산로 임도로 하산해 마무리한다.','Descend the Trail 1 forest road to finish.'),100,'tip',
            ('양 끝 들머리가 다르므로 이동 계획을 세운다.','Different trailheads at each end — plan transport.'))],
     cps=[(('자하곡 주차장','Jahagok lot'),('출발','Trailhead'),'badge-trailhead','해발 약 200m','0km',('주차','Parking')),
          (('화왕산','Hwawangsan'),('정상','Summit'),'badge-summit','928m','4.5km',('진달래 능선','Azalea ridge')),
          (('능선 종점','Ridge end'),('경유','Waypoint'),'badge-landmark','해발 약 600m','7.5km',('군락','Colony')),
          (('옥천 매표소','Okcheon gate'),('도착','Finish'),'badge-trailhead','해발 약 150m','약 9km',('주차','Parking'))],
     tips=[('backpack',('준비물','Gear'),('등산화·물 1.5L·행동식·헤드램프.','Boots, 1.5 L water, snacks, headlamp.')),
           ('book',('입산','Entry'),('별도 예약 불필요.','No reservation needed.')),
           ('shield',('주의','Cautions'),('4월 축제기 주차·셔틀 안내를 사전 확인.','Check festival parking and shuttle notices in April.'))],
     elev='M20 185 C150 160, 280 110, 420 80 S560 70, 660 60 S710 100, 740 120', peak=(660,60), elabel='928m',
     mnote='능선 완주', mstart='자하곡', mend='옥천',
     mpath='M120 330 C260 300, 400 200, 540 140 S680 90, 700 100', mnodes=[(120,330,10),(540,140,8),(700,100,12)]),
  ]),
 # ── 운장산 (v2, desc 정정: 진안·완주 운장대) ──
 'unjangsan': dict(ko_name='운장산', en_name='Unjangsan', alt='1,126m', b100=True,
  intro_ko='전북 진안·완주에 걸친 1,126m. 정상 운장대를 중심으로 서봉 칠성대·동봉 삼장봉이 이어지는 덕유산 줄기의 명산입니다.',
  intro_en='A 1,126 m mountain across Jinan and Wanju — the summit Unjangdae anchors a ridge of Seobong and Dongbong peaks on the Deogyu spine.',
  permit=('불필요', 'N/A'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('피암목재~운장대 왕복','Piamokjae–Unjangdae Round Trip'),
     dist=('약 5km','~5 km'), time=('2~2시간 30분','2–2.5 h'),
     flow=('피암목재','능선길','운장대 1,126m'),
     desc=('운장산 최단 코스 — 피암목재에서 정상 운장대까지 왕복 약 5km·2~2시간 30분.',
          'The shortest route: about 5 km round trip from Piamokjae pass to the Unjangdae summit in 2–2.5 hours.'),
     segs=[(1,('피암목재 → 능선길','Piamokjae → ridge'),'1.5km','40분',
            ('고개 주차에서 능선으로 붙는 짧은 오름.','A short pitch from the pass parking to the ridge.'),30,'tip',
            ('피암목재 주차 공간이 협소하다.','Parking at the pass is limited.')),
           (2,('능선길 → 운장대','Ridge → Unjangdae'),'1km','35분',
            ('완만한 능선을 따라 정상 운장대 1,126m에 오른다.','A gentle ridge to the 1,126 m summit.'),80,'tip',
            ('능선은 바람에 노출 — 방풍 준비.','Exposed ridge — bring a wind layer.')),
           (3,('운장대 → 하산','Summit → descent'),'2.5km','50분',
            ('온 길로 피암목재에 내려온다.','Return to the pass.'),100,'tip',
            ('칠성대(서봉) 조망을 확인하고 하산.','Enjoy the Seobong view before descending.'))],
     cps=[(('피암목재','Piamokjae'),('출발','Trailhead'),'badge-trailhead','해발 약 950m','0km',('고개 주차','Pass parking')),
          (('능선길','Ridge'),('경유','Waypoint'),'badge-landmark','해발 약 1,050m','1.5km',('없음','None')),
          (('운장대','Unjangdae'),('정상','Summit'),'badge-summit','1,126m','2.5km',('삼각점','Triangulation point'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1L·방풍.','Boots, 1 L water, wind shell.')),
           ('book',('입산','Entry'),('별도 예약 불필요.','No reservation needed.')),
           ('shield',('주의','Cautions'),('겨울 결빙 — 아이젠 대비.','Ice in winter — carry crampons.'))],
     elev='M20 180 C180 160, 330 115, 480 82 S660 48, 740 42', peak=(740,42), elabel='1,126m',
     mnote='최단 코스', mstart='피암목재', mend='운장대',
     mpath='M110 340 C240 318, 350 268, 460 212 S620 95, 695 55', mnodes=[(110,340,10),(460,212,8),(695,55,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('내처사 주차장 원점회귀','Naechoesa Circuit'),
     dist=('약 7.3km','~7.3 km'), time=('약 4시간','~4 h'),
     flow=('내처사 주차장','동봉 삼장봉','운장대 1,126m','서봉 칠성대','활목재'),
     desc=('내처사 주차장에서 동봉→운장대→서봉을 도는 실측 약 7.25km·3시간 53분 원점회귀 코스.',
          'A tracked 7.25 km / 3h53m loop from Naechoesa temple lot over the east peak, the summit and the west peak.'),
     segs=[(1,('내처사 → 동봉 삼장봉','Naechoesa → east peak'),'2.5km','1시간 20분',
            ('숲 오름으로 동봉 삼장봉(1,133m)에 오른다.','A forest climb to the east peak (1,133 m).'),40,'tip',
            ('삼장봉이 실질 최고봉 — 운장대가 정상 취급이다.','The east peak is actually higher; Unjangdae holds the official summit.')),
           (2,('동봉 → 운장대 → 서봉','East → Unjangdae → west'),'3km','1시간 20분',
            ('주능선을 따라 운장대와 서봉 칠성대를 잇는다.','The main ridge links Unjangdae and Seobong peaks.'),70,'warn',
            ('능선 바람 — 강풍 시 체온 관리.','Windy ridge — manage body heat.')),
           (3,('서봉 → 활목재 → 복귀','West → Hawalmokjae → exit'),'1.8km','1시간',
            ('활목재로 내려가 내처사로 원점 회귀한다.','Down to the pass and back to the temple lot.'),100,'tip',
            ('활목재~독자동 능선으로 종주 연계도 가능.','The pass links to the Doja-dong ridge for a longer day.'))],
     cps=[(('내처사 주차장','Naechoesa lot'),('출발','Trailhead'),'badge-trailhead','해발 약 700m','0km',('주차','Parking')),
          (('삼장봉','Sambong'),('경유','Waypoint'),'badge-summit','1,133m','2.5km',('봉우리','Peak')),
          (('운장대','Unjangdae'),('정상','Summit'),'badge-summit','1,126m','4km',('정상','Summit')),
          (('칠성대','Chilseongdae'),('경유','Waypoint'),'badge-landmark','1,120m','5.5km',('서봉','West peak')),
          (('내처사 주차장','Naechoesa lot'),('도착','Finish'),'badge-trailhead','해발 약 700m','7.25km',('주차','Parking'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1.5L·점심.','Boots, 1.5 L water, lunch.')),
           ('book',('입산','Entry'),('별도 예약 불필요.','No reservation needed.')),
           ('shield',('주의','Cautions'),('삼봉 연속 — 거리 감안 시간 배분.','Three peaks in a row — budget time for distance.'))],
     elev='M20 185 C150 165, 280 115, 420 82 S560 78, 660 62 S710 100, 740 125', peak=(660,62), elabel='1,126m',
     mnote='내처사 순환', mstart='내처사', mend='내처사',
     mpath='M120 320 C250 290, 360 220, 480 175 S640 90, 690 75 S610 240, 450 285 S230 320, 120 320', mnodes=[(120,320,10),(480,175,8),(690,75,12),(120,320,10)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('독자동~활목재 능선 종주','Doja-dong Ridge Traverse'),
     dist=('약 7.3km','~7.3 km'), time=('약 6시간','~6 h'),
     flow=('독자동','활목재','주능선','운장대 1,126m'),
     desc=('독자동 들머리에서 활목재를 넘어 주능선을 종주하는 실측 약 7.3km·5시간 55분(휴식 포함) 코스.',
          'A tracked 7.3 km / 5h55m traverse from Doja-dong over the pass and along the main ridge.'),
     segs=[(1,('독자동 → 활목재','Doja-dong → pass'),'2.5km','1시간 10분',
            ('마을 뒤 숲길로 고개를 넘는다.','Forest track from the village over the pass.'),25,'tip',
            ('독자동 주차·회차 공간 확인.','Check parking at the village.')),
           (2,('활목재 → 주능선','Pass → main ridge'),'2.3km','1시간 30분',
            ('오르내림이 반복되는 능선길이 길게 이어진다.','Long rolling ridge with repeated climbs.'),60,'warn',
            ('휴식 포함 실측 6시간 내외 — 체력 배분 관건.','Six hours with breaks — pacing decides the day.')),
           (3,('주능선 → 운장대','Ridge → Unjangdae'),'2.5km','1시간 30분',
            ('주능선을 따라 운장대에 오른 후 피암목재로 하산한다.','Climb the ridge to Unjangdae and descend to the pass.'),90,'tip',
            ('하산 들머리별 귀가 동선을 사전 확인.','Confirm your exit trailhead and transport.'))],
     cps=[(('독자동','Doja-dong'),('출발','Trailhead'),'badge-trailhead','해발 약 500m','0km',('마을 주차','Village parking')),
          (('활목재','Hawalmokjae'),('경유','Waypoint'),'badge-shelter','해발 약 900m','2.5km',('안부','Pass')),
          (('주능선','Main ridge'),('경유','Waypoint'),'badge-landmark','해발 약 1,050m','4.8km',('능선','Ridge')),
          (('운장대','Unjangdae'),('정상','Summit'),'badge-summit','1,126m','7.3km',('정상','Summit'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 2L·점심·헤드램프.','Boots, 2 L water, lunch, headlamp.')),
           ('book',('입산','Entry'),('별도 예약 불필요.','No reservation needed.')),
           ('shield',('주의','Cautions'),('원점회귀 아님 — 차량 셔틀 계획 필수.','Point-to-point — arrange a car shuttle.'))],
     elev='M20 190 C150 170, 290 125, 430 92 S570 70, 670 55 S720 95, 740 120', peak=(670,55), elabel='1,126m',
     mnote='독자동 종주', mstart='독자동', mend='운장대',
     mpath='M120 340 C250 310, 380 240, 500 185 S660 90, 700 65', mnodes=[(120,340,10),(500,185,8),(700,65,12)]),
  ]),
 # ── 비슬산 (v2) ──
 'biseulsan': dict(ko_name='비슬산', en_name='Biseulsan', alt='1,084m', b100=True,
  intro_ko='대구 달성·청도의 비슬산맥 최고봉 천왕봉 1,084m. 유가사 들머리와 악견의 능선, 억새·철쭉이 어우러진 도심 근교 명산입니다.',
  intro_en='Cheonwangbong, the 1,084 m high point of the Biseul range across Daegu Dalseong and Cheongdo — Yugasa trailhead, the famous rocky crest, and silver grass and azaleas near the city.',
  permit=('불필요', 'N/A'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('유가사~천왕봉 왕복','Yugasa–Cheonwangbong Round Trip'),
     dist=('약 5km','~5 km'), time=('약 3시간','~3 h'),
     flow=('유가사 주차장','능선길','천왕봉 1,084m'),
     desc=('대표 들머리 유가사에서 정상 천왕봉까지 휴식 포함 약 2시간 오름 — 왕복 3~4시간의 표준 코스.',
          'From the main trailhead at Yugasa, about two hours with breaks to Cheonwangbong — a 3–4 hour round trip.'),
     segs=[(1,('유가사 → 능선길','Yugasa → ridge'),'1.8km','1시간',
            ('고찰 유가사 뒤 숲길로 능선에 오른다.','Forest climb behind Yugasa temple to the ridge.'),40,'tip',
            ('주차장·화장실 정비 후 출발.','Use the lot and restrooms before starting.')),
           (2,('능선길 → 천왕봉','Ridge → Cheonwangbong'),'0.9km','50분',
            ('바위 능선을 지나 천왕봉 1,084m에 오른다.','Over rock crest to the 1,084 m summit.'),80,'warn',
            ('암반 구간 우천 시 주의.','Care on the rocks in rain.')),
           (3,('천왕봉 → 하산','Summit → descent'),'2.3km','1시간',
            ('온 길로 유가사에 내려온다.','Return the same way to the temple.'),100,'tip',
            ('봄 철쭉·가을 억새 시즌이 절정.','Best in azalea spring and silver-grass autumn.'))],
     cps=[(('유가사 주차장','Yugasa lot'),('출발','Trailhead'),'badge-trailhead','해발 약 500m','0km',('주차·화장실','Parking, restrooms')),
          (('능선길','Ridge'),('경유','Waypoint'),'badge-landmark','해발 약 850m','1.8km',('암능','Rock ridge')),
          (('천왕봉','Cheonwangbong'),('정상','Summit'),'badge-summit','1,084m','2.7km',('정상','Summit'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1L.','Boots, 1 L water.')),
           ('book',('입산','Entry'),('별도 예약 불필요.','No reservation needed.')),
           ('shield',('주의','Cautions'),('주말 오전 주차 혼잡.','Morning parking jams on weekends.'))],
     elev='M20 180 C180 158, 330 112, 480 80 S660 46, 740 42', peak=(740,42), elabel='1,084m',
     mnote='유가사 코스', mstart='유가사', mend='천왕봉',
     mpath='M110 340 C240 316, 350 266, 460 210 S620 95, 695 55', mnodes=[(110,340,10),(460,210,8),(695,55,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('유가사~천왕봉~월광봉~대견봉','Yugasa–Cheonwang–Wolgwang–Daegeon'),
     dist=('약 8km','~8 km'), time=('약 4시간','~4 h'),
     flow=('유가사','천왕봉 1,084m','월광봉','대견봉'),
     desc=('천왕봉~월광봉~대견봉을 잇는 능선 등반 — 구간 약 3.3km·1시간 20분대의 암능 하산이 백미.',
          'Ridge hiking linking Cheonwang, Wolgwang and Daegeon peaks — the 3.3 km rocky descent leg is the highlight.'),
     segs=[(1,('유가사 → 천왕봉','Yugasa → Cheonwangbong'),'2.7km','1시간 50분',
            ('표준 오름으로 정상에 오른다.','The standard climb to the summit.'),45,'tip',
            ('일찍 출발해 능선 여유를 확보.','Start early to bank time for the ridge.')),
           (2,('천왕봉 → 월광봉','Cheonwang → Wolgwang'),'1.6km','50분',
            ('완만한 능선 내림 후 월광봉에 닿는다.','Rolling descent to Wolgwang Peak.'),70,'tip',
            ('억새군락이 능선을 덮는 가을 최고.','Superb when the silver grass covers the ridge.')),
           (3,('월광봉 → 대견봉','Wolgwang → Daegeon'),'1.7km','1시간 20분',
            ('돌이 많은 산길 하산 — 이끼 낀 바위 주의.','A rocky descent — beware mossy stones.'),90,'warn',
            ('하산 급경사 — 지팡이 권장.','Steep — poles help.')),
           (4,('대견봉 → 하산 완료','Daegeon → exit'),'2km','1시간',
            ('들머리로 빠져 나와 복귀한다.','Exit the trail and arrange transport.'),100,'tip',
            ('원점회귀가 아님 — 귀가 동선 확인.','Not a loop — plan the return.'))],
     cps=[(('유가사 주차장','Yugasa lot'),('출발','Trailhead'),'badge-trailhead','해발 약 500m','0km',('주차','Parking')),
          (('천왕봉','Cheonwangbong'),('정상','Summit'),'badge-summit','1,084m','2.7km',('정상','Summit')),
          (('월광봉','Wolgwang'),('경유','Waypoint'),'badge-landmark','해발 약 1,000m','4.3km',('억새','Silver grass')),
          (('대견봉','Daegeonbong'),('도착','Finish'),'badge-trailhead','해발 약 600m','약 8km',('하산로','Exit trail'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1.5L·점심.','Boots, 1.5 L water, lunch.')),
           ('book',('입산','Entry'),('별도 예약 불필요.','No reservation needed.')),
           ('shield',('주의','Cautions'),('월광봉~대견봉 암반 하산 우천 시 위험.','The rocky descent is dangerous in rain.'))],
     elev='M20 170 C150 150, 280 100, 420 70 S560 85, 660 105 S710 140, 740 155', peak=(420,70), elabel='1,084m',
     mnote='능선 등반', mstart='유가사', mend='대견봉',
     mpath='M120 90 C240 120, 340 170, 460 220 S620 300, 680 335', mnodes=[(120,90,10),(460,220,8),(680,335,12)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('비슬산 완전 종주','Full Biseulsan Traverse'),
     dist=('약 12km','~12 km'), time=('약 5시간','~5 h'),
     flow=('유가사','천왕봉 1,084m','월광봉','대견봉','하산'),
     desc=('완전 종주 기준 산행시간 약 4시간 30분(초보 5시간). 비슬산 능선 전체를 잇는 하루 코스.',
          'The full traverse in about 4.5 hours (5 for beginners) — the whole Biseul ridge in a day.'),
     segs=[(1,('유가사 → 천왕봉','Yugasa → summit'),'2.7km','1시간 50분',
            ('표준 등반으로 정상 완등.','Standard climb to tag the summit.'),40,'tip',
            ('아침 일찍 — 종주는 거리가 관건.','Early start — distance is the challenge.')),
           (2,('천왕봉 → 월광봉 → 대견봉','Summit → ridge run'),'3.3km','1시간 20분',
            ('능선 3봉을 잇는 핵심 구간.','The core three-peak ridge.'),65,'warn',
            ('암반 구간 연속 — 장갑 권장.','Continuous rock — gloves help.')),
           (3,('대견봉 → 남부 능선','Daegeon → south ridge'),'3.5km','1시간 30분',
            ('남쪽 능선을 따라 억새밭을 지난다.','South through the silver-grass fields.'),85,'tip',
            ('가을 억새철 사진 명소.','A prime autumn photo leg.')),
           (4,('하산 완료','Exit'),'2.5km','1시간',
            ('남측 들머리로 하산해 마무리한다.','Descend the south trailhead to finish.'),100,'warn',
            ('거리 감안 일몰 전 하산 — 헤드램프 필수.','Finish by dusk — headlamp essential.'))],
     cps=[(('유가사 주차장','Yugasa lot'),('출발','Trailhead'),'badge-trailhead','해발 약 500m','0km',('주차','Parking')),
          (('천왕봉','Cheonwangbong'),('정상','Summit'),'badge-summit','1,084m','2.7km',('정상','Summit')),
          (('대견봉','Daegeonbong'),('경유','Waypoint'),'badge-landmark','해발 약 600m','6km',('능선','Ridge')),
          (('남부 능선','South ridge'),('경유','Waypoint'),'badge-landmark','해발 약 700m','9.5km',('억새밭','Silver grass')),
          (('남측 들머리','South trailhead'),('도착','Finish'),'badge-trailhead','해발 약 300m','약 12km',('하산로','Exit'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 2L·점심·헤드램프.','Boots, 2 L water, lunch, headlamp.')),
           ('book',('입산','Entry'),('별도 예약 불필요.','No reservation needed.')),
           ('shield',('주의','Cautions'),('완전 종주는 체력 요구 — 초보는 단축 코스 권장.','The full route demands fitness — beginners should shorten.'))],
     elev='M20 170 C140 148, 260 95, 400 68 S540 80, 640 100 S700 135, 740 150', peak=(400,68), elabel='1,084m',
     mnote='완전 종주', mstart='유가사', mend='남측 들머리',
     mpath='M120 80 C250 110, 370 180, 490 230 S650 310, 700 340', mnodes=[(120,80,10),(490,230,8),(700,340,12)]),
  ]),
})

F7.update({
 # ── 영취산 (v2) — 정체성 정정: 여수 진례봉 510m 진달래 명산 ──
 'yeongchwisan': dict(ko_name='영취산', en_name='Yeongchwisan', alt='510m', b100=False,
  intro_ko='여수의 진달래 명산 — 정상 진례봉 510m. 능선 전체가 진달래 군락이며 4월 영취산 진달래 축제로 유명합니다.',
  intro_en='Yeosu\'s azalea mountain, summit Jinnyebong at 510 m — the whole ridge is an azalea colony, famous for its April festival.',
  permit=('불필요', 'N/A'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('상암초교~진달래 군락지','Sangam School–Azalea Colony'),
     dist=('약 1.8~2.3km','1.8–2.3 km'), time=('약 1~1.5시간','1–1.5 h'),
     flow=('상암초교','봉우재','진달래 군락지','진례봉'),
     desc=('여수시 공식 상암초교 코스 — 군락지 접근이 가장 좋은 후기가 많은 짧은 산행(약 60~90분).',
          'The official city route from Sangam Elementary — often reviewed as the best colony access, 60–90 minutes.'),
     segs=[(1,('상암초교 → 봉우재','School → Bongwu pass'),'1km','30분',
            ('시가지에서 바로 숲길로 접어든다.','From town straight into forest.'),35,'tip',
            ('축제 기간 상암 방면 주차 통제가 있을 수 있다.','Festival-period parking controls may apply.')),
           (2,('봉우재 → 진달래 군락지','Pass → colony'),'0.8km','30분',
            ('능선을 타면 진달래 군락이 펼쳐진다.','The ridge opens onto the azalea colony.'),70,'warn',
            ('군락지 이탈 금지 — 포장 능선길 이용.','Stay on the paved ridge path — no stepping into colonies.')),
           (3,('군락지 → 진례봉','Colony → Jinnyebong'),'0.2~0.5km','15~20분',
            ('정상 진례봉 510m에서 여수 시가지와 바다 조망.','The 510 m summit looks over Yeosu and the sea.'),100,'tip',
            ('4월 첫째 주 축제가 절정.','The festival in early April is peak bloom.'))],
     cps=[(('상암초교','Sangam Elementary'),('출발','Trailhead'),'badge-trailhead','해발 약 60m','0km',('시가지 주차','Street parking')),
          (('봉우재','Bongwu pass'),('경유','Waypoint'),'badge-shelter','해발 약 300m','1km',('안부','Pass')),
          (('진례봉','Jinnyebong'),('정상','Summit'),'badge-summit','510m','약 2km',('여수 조망','Yeosu views'))],
     tips=[('backpack',('준비물','Gear'),('운동화·물 — 가벼운 산책.','Sneakers and water — an easy walk.')),
           ('book',('입산','Entry'),('무료·예약 불필요.','Free, no reservation.')),
           ('shield',('주의','Cautions'),('진달래 절기 주말 극심한 혼잡.','Extreme congestion on bloom weekends.'))],
     elev='M20 195 C180 180, 340 150, 500 115 S680 85, 740 78', peak=(740,78), elabel='510m',
     mnote='상암초교 코스', mstart='상암초교', mend='진례봉',
     mpath='M110 350 C250 320, 380 260, 500 200 S660 100, 700 80', mnodes=[(110,350,10),(500,200,8),(700,80,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('돌고개~진례봉 왕복','Dolgae Pass Round Trip'),
     dist=('약 4.4km','~4.4 km'), time=('약 2시간 20분','~2 h 20 m'),
     flow=('돌고개 주차장','능선','진례봉 510m'),
     desc=('대표 들머리 돌고개에서 정상 진례봉까지 왕복 — 안내 기준 1.9km·약 70분대 오름.',
          'The main trailhead at Dolgae: about 1.9 km and 70-odd minutes to the summit, out and back.'),
     segs=[(1,('돌고개 → 능선','Dolgae → ridge'),'1km','35분',
            ('주차장에서 능선길로 오른다.','From the lot up to the ridge.'),40,'tip',
            ('돌고개 주차장은 축제기 만차.','The lot fills during the festival.')),
           (2,('능선 → 진례봉','Ridge → Jinnyebong'),'0.9km','35분',
            ('진달래 능선을 따라 정상에 오른다.','Along the azalea ridge to the top.'),85,'tip',
            ('능선에서 바다 조망이 열린다.','Sea views open on the ridge.')),
           (3,('진례봉 → 하산','Summit → descent'),'1.9km','70분',
            ('온 길로 돌고개에 내려온다.','Return to the pass.'),100,'tip',
            ('축제 기간 셔틀버스 운행 여부 확인.','Check festival shuttle operations.'))],
     cps=[(('돌고개 주차장','Dolgae lot'),('출발','Trailhead'),'badge-trailhead','해발 약 150m','0km',('주차장','Parking')),
          (('능선','Ridge'),('경유','Waypoint'),'badge-landmark','해발 약 350m','1km',('진달래','Azaleas')),
          (('진례봉','Jinnyebong'),('정상','Summit'),'badge-summit','510m','1.9km',('정상','Summit'))],
     tips=[('backpack',('준비물','Gear'),('운동화·물 1L.','Sneakers, 1 L water.')),
           ('book',('입산','Entry'),('무료·예약 불필요.','Free, no reservation.')),
           ('shield',('주의','Cautions'),('축제 기간 차량 진입 통제 — 대중교통 권장.','Vehicle controls during the festival — use transit.'))],
     elev='M20 190 C180 172, 340 135, 500 100 S680 70, 740 62', peak=(740,62), elabel='510m',
     mnote='돌고개 코스', mstart='돌고개', mend='진례봉',
     mpath='M110 345 C240 320, 350 265, 460 210 S620 100, 695 62', mnodes=[(110,345,10),(460,210,8),(695,62,12)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('영취산 능선 완주','Full Ridge Traverse'),
     dist=('약 6.7km','~6.7 km'), time=('약 2시간 30분','~2.5 h'),
     flow=('중흥동 GS칼텍스 후문','억새평원','진례산 정상','능선 완주'),
     desc=('여수시 공식 기준 능선 완주 약 6.7km·약 2시간 30분. GS칼텍스 후문에서 억새평원·정상을 지르는 코스.',
          'The official full ridge: about 6.7 km and 2.5 hours from the GS Caltex rear gate over the silver-grass field to the summit.'),
     segs=[(1,('GS칼텍스 후문 → 억새평원','Rear gate → silver grass'),'2.2km','약 70분',
            ('안내 기준 70분·2.2km 오름 — 봄엔 진달래, 가을엔 억새.','A signposted 70-minute, 2.2 km climb — azaleas in spring, silver grass in fall.'),50,'tip',
            ('예비군 훈련장 인근 — 지정 코스 준수.','Near a reserve-training ground — keep to the marked trail.')),
           (2,('억새평원 → 진례산 정상','Silver grass → summit'),'1km','40분',
            ('평원 능선을 지나 진례산 정상에 오른다.','Over the plateau field to the summit.'),80,'warn',
            ('바람 강한 개방 능선.','An exposed, windy ridge.')),
           (3,('정상 → 능선 완주 → 하산','Summit → traverse → exit'),'3.5km','1시간 20분',
            ('능선을 완주해 맞은편 들머리로 빠진다.','Complete the ridge and exit at the far trailhead.'),100,'tip',
            ('맞은편 들머리 교통 확인 후 진행.','Check transport at the exit before committing.'))],
     cps=[(('GS칼텍스 후문','GS Caltex rear gate'),('출발','Trailhead'),'badge-trailhead','해발 약 100m','0km',('시가지 접근','Urban access')),
          (('억새평원','Silver-grass field'),('경유','Waypoint'),'badge-landmark','해발 약 350m','2.2km',('평원','Field')),
          (('진례산 정상','Summit'),('정상','Summit'),'badge-summit','510m','3.2km',('정상','Summit')),
          (('맞은편 들머리','Far trailhead'),('도착','Finish'),'badge-trailhead','해발 약 150m','6.7km',('하산로','Exit'))],
     tips=[('backpack',('준비물','Gear'),('운동화·물 1L·자외선 대비.','Sneakers, 1 L water, sun protection.')),
           ('book',('입산','Entry'),('무료·예약 불필요.','Free, no reservation.')),
           ('shield',('주의','Cautions'),('4월 축제·10월 억새철 혼잡 — 평일 권장.','Crowded in April and October — weekdays are best.'))],
     elev='M20 195 C170 178, 330 140, 490 105 S670 75, 740 68', peak=(740,68), elabel='510m',
     mnote='능선 완주', mstart='GS칼텍스 후문', mend='맞은편 들머리',
     mpath='M120 330 C260 300, 380 230, 500 180 S660 90, 700 70', mnodes=[(120,330,10),(500,180,8),(700,70,12)]),
  ]),
 # ── 청량산 (v2) — 정체성 정정: 봉화·안동 의상봉 869.7m ──
 'cheongnyangsan': dict(ko_name='청량산', en_name='Cheongnyangsan', alt='869.7m', b100=True,
  intro_ko='경북 봉화·안동의 기암 명산 — 정상 의상봉 869.7m. 「영남 소금강」이라 불린 절경과 청량사·금타굴이 어우러집니다.',
  intro_en='A crag wonder across Bonghwa and Andong — the summit Uisangbong at 869.7 m, called the Yeongnam Geumgang, with Cheongnyangsa temple and Geumthagul cave.',
  permit=('불필요', 'N/A'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('입석~청량사 「구도의 길」','Ipseok–Cheongnyangsa Path'),
     dist=('1.3km','1.3 km'), time=('30~40분','30–40 min'),
     flow=('청량산 입석','원효대사 구도의 길','청량사'),
     desc=('청량산 입석에서 청량사까지 1.3km·30~40분 — 의상대사 창건 설화가 깃든 「원효대사 구도의 길」.',
          'From the Ipseok standing rock to Cheongnyangsa temple — 1.3 km in 30–40 minutes on the pilgrimage path of Master Wonhyo.'),
     segs=[(1,('입석 출발','From Ipseok'),'0.3km','10분',
            ('기암 입석을 지나 등산로로 들어선다.','Past the standing rock onto the trail.'),25,'tip',
            ('청량사 주차장·매표 확인.','Check temple parking and gate.')),
           (2,('구도의 길','The pilgrim path'),'1km','20~30분',
            ('기암괴석 사이 숲길이 청량사로 이어진다.','Crag-side forest to the temple.'),70,'tip',
            ('사찰 예법 준수 — 경내 정숙.','Be quiet and respectful in the temple.')),
           (3,('청량사 도착','At the temple'),'—','20~30분',
            ('사찰과 금타굴 일대를 둘러보며 마무리한다.','Explore the temple and cave area to finish.'),100,'tip',
            ('금타굴 방문 가능 여부는 사찰 안내 확인.','Ask the temple about cave access.'))],
     cps=[(('청량산 입석','Ipseok'),('출발','Trailhead'),'badge-trailhead','해발 약 300m','0km',('주차','Parking')),
          (('구도의 길','Pilgrim path'),('경유','Waypoint'),'badge-landmark','해발 약 450m','1km',('기암','Crags')),
          (('청량사','Cheongnyangsa'),('도착','Finish'),'badge-landmark','해발 약 550m','1.3km',('사찰·금타굴','Temple, cave'))],
     tips=[('backpack',('준비물','Gear'),('운동화·물 — 짧은 산책.','Sneakers, water — a short walk.')),
           ('book',('입산','Entry'),('사찰 문화재 관람 안내 준수.','Follow temple heritage guidance.')),
           ('shield',('주의','Cautions'),('기암 구간 낙석 주의.','Rockfall zones among the crags.'))],
     elev='M20 195 C200 180, 420 150, 600 120 S710 105, 740 100', peak=(740,100), elabel='약 550m',
     mnote='입석~청량사', mstart='입석', mend='청량사',
     mpath='M110 350 C260 322, 400 262, 520 205 S680 115, 710 100', mnodes=[(110,350,10),(520,205,8),(710,100,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('청량사~하늘다리~의상봉 단축 종주','Temple–Sky Bridge–Uisangbong'),
     dist=('약 5km','~5 km'), time=('약 4시간','~4 h'),
     flow=('청량사','뒷실고개','하늘다리','의상봉 869.7m','청량폭포'),
     desc=('단축 종주 — 청량사에서 뒷실고개·하늘다리를 지나 의상봉에 오르고 청량폭포로 하산하는 약 4시간 코스.',
          'The shortened circuit: temple to the back pass and Sky Bridge, up Uisangbong and down past Cheongnyang Falls — about four hours.'),
     segs=[(1,('청량사 → 뒷실고개','Temple → back pass'),'1.5km','50분',
            ('사찰 뒤 숲길로 고개에 오른다.','Forest behind the temple to the pass.'),35,'tip',
            ('고개에서 능선·폭포 갈림 표지 확인.','Check junction signs at the pass.')),
           (2,('뒷실고개 → 하늘다리','Pass → Sky Bridge'),'1km','40분',
            ('기암 능선의 하늘다리 — 청량산 절경의 핵심.','The crag-ridge Sky Bridge — the scenic heart.'),65,'warn',
            ('다리·암반 구간 우천 시 통행 주의.','Care on the bridge and slabs in rain.')),
           (3,('하늘다리 → 의상봉','Bridge → Uisangbong'),'1.2km','50분',
            ('연적봉 방면 능선을 지나 의상봉 869.7m 완등.','Over the ridge to the 869.7 m summit.'),90,'tip',
            ('정상에서 청량산 기암군 조망.','Summit views over the crag fields.')),
           (4,('의상봉 → 청량폭포 하산','Summit → falls descent'),'1.3km','50분',
            ('청량폭포를 지나 주차장으로 하산한다.','Down past the falls to the lot.'),100,'tip',
            ('폭포 주변 바위 미끄럼 주의.','Wet rocks near the falls.'))],
     cps=[(('청량사','Cheongnyangsa'),('출발','Trailhead'),'badge-landmark','해발 약 550m','0km',('사찰·주차','Temple, parking')),
          (('뒷실고개','Back pass'),('경유','Waypoint'),'badge-shelter','해발 약 600m','1.5km',('갈림길','Junction')),
          (('하늘다리','Sky Bridge'),('경유','Waypoint'),'badge-landmark','해발 약 750m','2.5km',('기암 조망','Crag views')),
          (('의상봉','Uisangbong'),('정상','Summit'),'badge-summit','869.7m','3.7km',('정상','Summit')),
          (('청량폭포','Cheongnyang Falls'),('도착','Finish'),'badge-landmark','해발 약 350m','약 5km',('폭포','Waterfall'))],
     tips=[('backpack',('준비물','Gear'),('등산화·물 1L.','Boots, 1 L water.')),
           ('book',('입산','Entry'),('별도 예약 불필요 — 사찰 주차 요금 확인.','No permit; check temple parking fees.')),
           ('shield',('주의','Cautions'),('기암 능선 — 낙석·미끄럼 주의 구간 다수.','Crag ridge with frequent rockfall and slip zones.'))],
     elev='M20 185 C170 168, 320 130, 470 100 S650 68, 740 60', peak=(740,60), elabel='869.7m',
     mnote='단축 종주', mstart='청량사', mend='의상봉',
     mpath='M110 335 C240 310, 350 258, 460 205 S620 92, 695 55', mnodes=[(110,335,10),(460,205,8),(695,55,12)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('청량산 완전 종주','Full Cheongnyangsan Traverse'),
     dist=('약 14.7km','~14.7 km'), time=('약 6시간','~6 h'),
     flow=('청량사','응진전','어풍대','경일봉','자소봉','탁필봉','연적봉','하늘다리','의상봉 869.7m','청량폭포'),
     desc=('완전 종주 약 14.7km·약 6시간 — 응진전·풍혈대·어풍대를 거쳐 경일봉·자소봉·탁필봉·연적봉을 잇고 하늘다리·의상봉으로 마무리.',
          'The full 14.7 km traverse in about six hours — past Eungjinjeon and the wind caves to Gyeongil, Jaso, Takpil and Yeonjeok peaks, finishing over the Sky Bridge to Uisangbong.'),
     segs=[(1,('청량사 → 응진전 → 어풍대','Temple → Eungjinjeon → Wind Rock'),'3.5km','1시간 30분',
            ('사찰 권역 기암군을 차례로 지난다.','Past the temple\'s crag sights in sequence.'),30,'tip',
            ('완전 종주는 이른 아침 출발이 원칙.','Start early for the full route.')),
           (2,('어풍대 → 경일봉 → 자소봉','Wind Rock → summit run'),'4.5km','2시간',
            ('북 능선 봉우리들을 잇는 롱구간.','A long leg linking the northern peaks.'),60,'warn',
            ('구간이 길고 물이 없다 — 물 2L.','Long, waterless — carry 2 L.')),
           (3,('자소봉 → 탁필봉 → 연적봉','Jaso → Takpil → Yeonjeok'),'3.5km','1시간 20분',
            ('기암 봉우리 연속 — 청량산의 백미.','A run of crag peaks — the mountain at its best.'),80,'warn',
            ('암반 노출 구간 강풍 시 주의.','Exposed slabs — care in strong wind.')),
           (4,('연적봉 → 하늘다리 → 의상봉 → 하산','Yeonjeok → bridge → summit → out'),'3.2km','1시간 10분',
            ('하늘다리와 의상봉을 마지막으로 통과해 폭포로 하산한다.','Finish over the Sky Bridge and summit, down past the falls.'),100,'tip',
            ('봉화군 1코스(12.7km·9시간) 등 대체 코스도 공식 안내.','The county also lists longer official routes.'))],
     cps=[(('청량사','Cheongnyangsa'),('출발','Trailhead'),'badge-landmark','해발 약 550m','0km',('주차','Parking')),
          (('어풍대','Eopungdae'),('경유','Waypoint'),'badge-landmark','해발 약 600m','3.5km',('기암','Crag')),
          (('자소봉','Jasobong'),('경유','Waypoint'),'badge-summit','해발 약 800m','8km',('봉우리','Peak')),
          (('연적봉','Yeonjeokbong'),('경유','Waypoint'),'badge-landmark','해발 약 820m','11.5km',('기암','Crag')),
          (('의상봉','Uisangbong'),('정상','Summit'),'badge-summit','869.7m','13.5km',('정상','Summit')),
          (('청량폭포','Falls'),('도착','Finish'),'badge-landmark','해발 약 350m','14.7km',('폭포·주차','Falls, parking'))],
     tips=[('backpack',('준비물','Gear'),('등산화·물 2L·점심·헤드램프·장갑.','Boots, 2 L water, lunch, headlamp, gloves.')),
           ('book',('입산','Entry'),('봉화군 공식 탐방코스 안내 준수.','Follow official county trail notices.')),
           ('shield',('주의','Cautions'),('기암 종주 — 우천·강풍 시 단축 코스로 대체.','In rain or wind, switch to the shortened circuit.'))],
     elev='M20 180 C140 158, 270 108, 410 80 S550 88, 650 62 S710 95, 740 120', peak=(650,62), elabel='869.7m',
     mnote='완전 종주', mstart='청량사', mend='의상봉',
     mpath='M120 330 C250 300, 370 220, 490 170 S650 80, 700 62', mnodes=[(120,330,10),(490,170,8),(700,62,12)]),
  ]),
 # ── 백암산 (v3) — 정체성 정정: 장성·순창 상왕봉 741.2m ──
 'baekamsan': dict(ko_name='백암산', en_name='Baegamsan', alt='741.2m', b100=True,
  intro_ko='전남 장성·전북 순창 경계의 상왕봉 741.2m. 내장산 줄기의 능선 산으로 백양사·구암사 들머리가 유명합니다.',
  intro_en='Sangwangbong at 741.2 m on the Jangseong–Sunchang border — a ridge mountain of the Naejangsan spine with the famous Baekyangsa and Guamsa trailheads.',
  permit=('불필요', 'N/A'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('구암사 최단 코스','Guamsa Short Route'),
     dist=('약 5.1km','~5.1 km'), time=('3시간 30분~3시간 40분','3.5 h'),
     flow=('구암사 주차장','백학송 전망대','상왕봉 741.2m'),
     desc=('실측 왕복 5.1km·3시간 38분(휴식 포함)의 최단 코스 — 난이도 하~중, 경사 구간이 짧아 무난하다.',
          'The shortest route: a tracked 5.1 km, 3h38m round trip rated easy-moderate with short pitches only.'),
     segs=[(1,('구암사 → 백학송 전망대','Guamsa → white-pine lookout'),'1.8km','50분',
            ('고찰 구암사 뒤 숲길로 전망대에 오른다.','Forest behind Guamsa temple to the lookout.'),35,'tip',
            ('구암사 주차장 이용.','Parking at the temple.')),
           (2,('전망대 → 상왕봉','Lookout → Sangwangbong'),'0.8km','40분',
            ('마지막 오름으로 상왕봉 741.2m에 오른다.','The final pitch to Sangwangbong, 741.2 m.'),80,'tip',
            ('정상에서 백학봉 2.3km·순창 새재 2.4km 이정표.','Summit signposts: 2.3 km to Baekhakbong, 2.4 km to the pass.')),
           (3,('상왕봉 → 하산','Summit → descent'),'2.5km','1시간 20분',
            ('온 길로 구암사에 내려온다.','Return the same way to the temple.'),100,'tip',
            ('구암사 경내 산책으로 마무리.','Finish with a temple stroll.'))],
     cps=[(('구암사 주차장','Guamsa lot'),('출발','Trailhead'),'badge-trailhead','해발 약 250m','0km',('주차·사찰','Parking, temple')),
          (('백학송 전망대','Pine lookout'),('경유','Waypoint'),'badge-landmark','해발 약 500m','1.8km',('전망','View')),
          (('상왕봉','Sangwangbong'),('정상','Summit'),'badge-summit','741.2m','2.6km',('정상','Summit'))],
     tips=[('backpack',('준비물','Gear'),('등산화·물 1L.','Boots, 1 L water.')),
           ('book',('입산','Entry'),('별도 예약 불필요 — 사찰 주차 요금 확인.','No permit; check temple parking fees.')),
           ('shield',('주의','Cautions'),('하~중 난이도라도 거리 감안 수분 보충.','Easy grade, but hydrate for the distance.'))],
     elev='M20 190 C180 170, 340 128, 500 92 S680 55, 740 48', peak=(740,48), elabel='741.2m',
     mnote='구암사 코스', mstart='구암사', mend='상왕봉',
     mpath='M110 345 C240 318, 350 265, 460 208 S620 92, 695 55', mnodes=[(110,345,10),(460,208,8),(695,55,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('백양사 능선 원점회귀','Baekyangsa Ridge Loop'),
     dist=('약 8km','~8 km'), time=('약 4시간','~4 h'),
     flow=('백양사 주차장','약사암','백학봉','도집봉','상왕봉 741.2m','사자봉'),
     desc=('백양사에서 약사암을 지나 백학봉·도집봉·상왕봉·사자봉을 도는 능선 순환 — 백학봉까지 약 1시간 15분.',
          'The Baekyangsa loop past Yaksaam hermitage over Baekhak, Dojip, Sangwang andaja peaks — about 1h15m to the first peak.'),
     segs=[(1,('백양사 → 약사암 → 백학봉','Temple → Yaksaam → Baekhakbong'),'2.5km','1시간 15분',
            ('유명 고찰 백양사 경내를 지나 능선에 오른다.','Through the famed Baekyangsa temple grounds to the ridge.'),35,'tip',
            ('백양사는 사찰 문화재 관람객과 동선 공유.','The trailhead shares space with temple visitors.')),
           (2,('백학봉 → 도집봉 → 상왕봉','Baekhak → Dojip → Sangwang'),'2.8km','1시간 20분',
            ('능선 봉우리 3연 — 봄 진달래·가을 단풍이 절경.','Three ridge peaks — azaleas in spring, maples in fall.'),70,'warn',
            ('능선 바람 — 방풍 준비.','Windy ridge — wind layer.')),
           (3,('상왕봉 → 사자봉 → 백양사','Sangwang → Saja → temple'),'2.7km','1시간 20분',
            ('사자봉을 지나 백양사로 원점 회귀한다.','Over the lion peak back to the temple.'),100,'tip',
            ('「봄엔 백양산, 가을엔 내장산」이라 불리는 경관.','The scenery earns its spring-and-autumn reputation.'))],
     cps=[(('백양사 주차장','Baekyangsa lot'),('출발','Trailhead'),'badge-trailhead','해발 약 300m','0km',('주차·화장실','Parking, restrooms')),
          (('약사암','Yaksaam'),('경유','Waypoint'),'badge-landmark','해발 약 400m','1km',('암자','Hermitage')),
          (('백학봉','Baekhakbong'),('경유','Waypoint'),'badge-summit','해발 약 640m','2.5km',('봉우리','Peak')),
          (('상왕봉','Sangwangbong'),('정상','Summit'),'badge-summit','741.2m','5.3km',('정상','Summit')),
          (('사자봉','Sajabong'),('경유','Waypoint'),'badge-landmark','해발 약 600m','6.8km',('봉우리','Peak')),
          (('백양사 주차장','Baekyangsa lot'),('도착','Finish'),'badge-trailhead','해발 약 300m','약 8km',('주차','Parking'))],
     tips=[('backpack',('준비물','Gear'),('등산화·물 1.5L·점심.','Boots, 1.5 L water, lunch.')),
           ('book',('입산','Entry'),('내장산국립공원 구역 — 공단 안내 준수.','Inside Naejangsan National Park — follow KNPS notices.')),
           ('shield',('주의','Cautions'),('단풍철 주차 혼잡 — 이른 아침.','Foliage-season parking jams — go early.'))],
     elev='M20 190 C160 170, 310 125, 460 88 S640 55, 730 48 S740 100, 740 130', peak=(730,48), elabel='741.2m',
     mnote='백양사 순환', mstart='백양사', mend='백양사',
     mpath='M120 330 C250 302, 370 230, 490 180 S650 88, 695 68 S620 250, 460 290 S230 330, 120 330', mnodes=[(120,330,10),(490,180,8),(695,68,12),(120,330,10)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('백암산 완전 종주','Full Baegamsan Traverse'),
     dist=('약 10km','~10 km'), time=('약 5시간','~5 h'),
     flow=('구암사','백학봉','상왕봉 741.2m','사자봉','백양사'),
     desc=('전체 종주 약 10km·약 5시간 — 구암사와 백양사 양 들머리를 잇는 하루 종주.',
          'The full 10 km traverse in about five hours, linking the Guamsa and Baekyangsa trailheads.'),
     segs=[(1,('구암사 → 백학봉','Guamsa → Baekhakbong'),'3.2km','1시간 30분',
            ('최단 코스 오름길로 능선에 오른다.','The short-route climb to the ridge.'),35,'tip',
            ('양 들머리 셔틀을 사전 계획.','Plan the two-trailhead shuttle.')),
           (2,('백학봉 → 상왕봉 → 사자봉','Baekhak → summit → Saja'),'4.3km','2시간',
            ('주능선 3봉 완등 — 백암산의 핵심.','The three main peaks — the heart of the mountain.'),70,'warn',
            ('능선 연속 오르내림.','Relentless ridge ups and downs.')),
           (3,('사자봉 → 백양사 하산','Saja → Baekyangsa descent'),'2.5km','1시간',
            ('백양사 경내로 하산해 종주를 마친다.','Descend into Baekyangsa to finish.'),100,'tip',
            ('하산 후 사찰 탐방·식사로 마무리.','End with the temple and a meal.'))],
     cps=[(('구암사 주차장','Guamsa lot'),('출발','Trailhead'),'badge-trailhead','해발 약 250m','0km',('주차','Parking')),
          (('백학봉','Baekhakbong'),('경유','Waypoint'),'badge-summit','해발 약 640m','3.2km',('봉우리','Peak')),
          (('상왕봉','Sangwangbong'),('정상','Summit'),'badge-summit','741.2m','5.5km',('정상','Summit')),
          (('사자봉','Sajabong'),('경유','Waypoint'),'badge-landmark','해발 약 600m','7.5km',('봉우리','Peak')),
          (('백양사','Baekyangsa'),('도착','Finish'),'badge-landmark','해발 약 300m','약 10km',('사찰·주차','Temple, parking'))],
     tips=[('backpack',('준비물','Gear'),('등산화·물 1.5~2L·점심.','Boots, 1.5–2 L water, lunch.')),
           ('book',('입산','Entry'),('국립공원 구역 — 공단 안내 준수.','National park — follow KNPS notices.')),
           ('shield',('주의','Cautions'),('원점회귀 아님 — 차량 셔틀 필수.','Point-to-point — a car shuttle is required.'))],
     elev='M20 185 C150 162, 280 112, 420 82 S560 75, 660 55 S710 95, 740 125', peak=(660,55), elabel='741.2m',
     mnote='완전 종주', mstart='구암사', mend='백양사',
     mpath='M120 330 C250 300, 380 220, 500 170 S660 80, 700 65', mnodes=[(120,330,10),(500,170,8),(700,65,12)]),
  ]),
})


F7.update({
 # ── 용문산 (v4) ──
 'yongmunsan': dict(ko_name='용문산', en_name='Yongmunsan', alt='1,157m', b100=True,
  intro_ko='양평의 진산 1,157m(가섭봉). 천년 은행나무의 용문사에서 마당바위를 거쳐 정상에 이르는 경기 동부의 대표 산입니다.',
  intro_en='Yangpyeong\'s guardian peak at 1,157 m (Gaseopbong) — the millennium ginkgo of Yongmunsa temple, then Madang Rock to the summit.',
  permit=('불필요', 'N/A'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('최단 코스 왕복','Shortest Route Round Trip'),
     dist=('약 3.4km','~3.4 km'), time=('약 2시간','~2 h'),
     flow=('최단 들머리','전망 능선','용문산 정상'),
     desc=('안내되는 1.7km 최단 등반로의 왕복 — 조망이 좋아 짧게 정상을 밟는 코스.',
          'Out and back on the signposted 1.7 km shortest route — big views for a short day.'),
     segs=[(1,('최단 들머리 → 능선','Trailhead → ridge'),'0.8km','25분',
            ('등산로 입구에서 바로 능선으로 붙는다.','Straight from the lot to the ridge.'),35,'tip',
            ('최단 코스 주차 공간이 협소하다.','Parking at this trailhead is limited.')),
           (2,('능선 → 정상','Ridge → summit'),'0.9km','35분',
            ('개방된 전망 능선을 따라 오른다.','Up an open viewpoint ridge.'),80,'tip',
            ('서쪽으로 양평 분지 조망.','Yangpyeong basin views west.')),
           (3,('정상 → 하산','Summit → descent'),'1.7km','50분',
            ('온 길로 내려온다.','Return the same way.'),100,'tip',
            ('용문사 경유로 이어가려면 1번 코스로.','Continue via the temple on Route 1 if time allows.'))],
     cps=[(('최단 들머리','Short trailhead'),('출발','Trailhead'),'badge-trailhead','해발 약 700m','0km',('주차 협소','Limited parking')),
          (('전망 능선','View ridge'),('경유','Waypoint'),'badge-landmark','해발 약 900m','0.8km',('전망','View')),
          (('용문산','Yongmunsan'),('정상','Summit'),'badge-summit','1,157m','1.7km',('정상','Summit'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1L.','Boots, 1 L water.')),
           ('book',('입산','Entry'),('별도 예약 불필요.','No reservation needed.')),
           ('shield',('주의','Cautions'),('전망 능선 바람 — 방풍.','Exposed ridge — wind layer.'))],
     elev='M20 180 C180 160, 330 115, 480 82 S660 48, 740 42', peak=(740,42), elabel='1,157m',
     mnote='최단 코스', mstart='최단 들머리', mend='정상',
     mpath='M110 340 C240 316, 350 264, 460 208 S620 95, 695 55', mnodes=[(110,340,10),(460,208,8),(695,55,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('용문사~마당바위~가섭봉','Yongmunsa–Madang Rock–Gaseopbong'),
     dist=('약 9km','~9 km'), time=('5~6시간','5–6 h'),
     flow=('관광단지 주차장','용문사','사미기봉','마당바위','가섭봉 1,157m'),
     desc=('대표 1번 코스 — 용문사 관광단지에서 천년 은행나무의 용문사, 사미기봉(약 870m), 마당바위를 거쳐 가섭봉 정상. 실측 8.8~11.1km·6시간 내외.',
          'The classic Route 1: from the tourist-lot through Yongmunsa and its millennium ginkgo, past Samigibong (~870 m) and Madang Rock to the summit — 8.8–11.1 km, about six hours by logs.'),
     segs=[(1,('관광단지 → 용문사','Lot → Yongmunsa'),'1.2km','30분',
            ('관광단지 주차장에서 천년고찰 용문사로 오른다.','From the lot up to the ancient temple.'),15,'tip',
            ('주차장-용문사 도보 구간 — 유료 주차.','Paid lot; short walk to the temple.')),
           (2,('용문사 → 사미기봉 → 마당바위','Temple → Samigi → Madang Rock'),'3.5km','2시간',
            ('은행나무 경내 뒤 능선으로 사미기봉과 마당바위를 지난다.','Behind the ginkgo courtyard over Samigibong to Madang Rock.'),55,'warn',
            ('마당바위~가섭봉 1.5km가 가장 험난하다.','The 1.5 km past Madang Rock is the roughest leg.')),
           (3,('마당바위 → 가섭봉','Madang Rock → summit'),'1.5km','1시간',
            ('암능·급경사를 지나 정상 1,157m 완등.','Crags and steep pitches to the 1,157 m top.'),85,'warn',
            ('우천 시 암반 매우 미끄럽다.','Slabs are treacherous wet.')),
           (4,('가섭봉 → 하산','Summit → descent'),'3km','1시간 30분',
            ('내려와 관광단지로 원점 회귀한다.','Down and back to the lot.'),100,'tip',
            ('하산 후 용문사 탐방·음식으로 마무리.','End with the temple and local food.'))],
     cps=[(('관광단지 주차장','Tourist lot'),('출발','Trailhead'),'badge-trailhead','해발 약 300m','0km',('주차·화장실·매점','Parking, restrooms, shops')),
          (('용문사','Yongmunsa'),('경유','Waypoint'),'badge-landmark','해발 약 460m','1.2km',('천년 은행나무','Millennium ginkgo')),
          (('사미기봉','Samigibong'),('경유','Waypoint'),'badge-landmark','약 870m','3km',('봉우리','Peak')),
          (('마당바위','Madang Rock'),('경유','Waypoint'),'badge-landmark','해발 약 1,000m','4.7km',('바위 전망','Rock view')),
          (('가섭봉','Gaseopbong'),('정상','Summit'),'badge-summit','1,157m','6.2km',('정상','Summit'))],
     tips=[('backpack',('준비물','Gear'),('등산화·물 1.5L·점심·장갑.','Boots, 1.5 L water, lunch, gloves.')),
           ('book',('입산','Entry'),('별도 예약 불필요 — 주차 요금 확인.','No permit; check parking fees.')),
           ('shield',('주의','Cautions'),('마당바위~정상 암능 구간 우천 시 위험.','The crag leg is dangerous in rain.'))],
     elev='M20 192 C160 178, 300 148, 430 118 S560 95, 660 52 S710 50, 740 46', peak=(740,46), elabel='1,157m',
     mnote='용문사 1번 코스', mstart='관광단지', mend='가섭봉',
     mpath='M110 345 C230 322, 340 280, 450 240 S610 110, 690 60', mnodes=[(110,345,10),(450,240,8),(690,60,12)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('용문산~유명산 종주','Yongmunsan–Yumyeongsan Traverse'),
     dist=('약 18km','~18 km'), time=('7~8시간','7–8 h'),
     flow=('용문사','가섭봉 1,157m','능선 종주','유명산 862m'),
     desc=('용문산과 유명산을 잇는 경기 동부 대표 종주 — 약 18km·7~8시간.',
          'The great eastern-Gyeonggi traverse linking Yongmunsan and Yumyeongsan — about 18 km and 7–8 hours.'),
     segs=[(1,('용문사 → 가섭봉','Temple → summit'),'6.2km','3시간',
            ('대표 코스로 정상을 먼저 밟는다.','Tag the summit via the classic route.'),35,'warn',
            ('종주 거리 감안 새벽 출발.','Dawn start for the distance.')),
           (2,('가섭봉 → 능선 종주','Summit → ridge run'),'8km','3~3.5시간',
            ('용문-유명 능선을 길게 이어간다.','The long ridge between the two peaks.'),65,'warn',
            ('중간 이탈로 제한 — 체력 관리 필수.','Few exits — manage your reserves.')),
           (3,('능선 → 유명산 정상','Ridge → Yumyeongsan'),'3.8km','1시간 30분',
            ('유명산 862m에 오르며 종주를 마무리한다.','Finish on Yumyeongsan at 862 m.'),90,'tip',
            ('하산은 유명산 휴양림 방면.','Descend toward the recreation forest.'))],
     cps=[(('용문사 관광단지','Temple lot'),('출발','Trailhead'),'badge-trailhead','해발 약 300m','0km',('주차','Parking')),
          (('가섭봉','Gaseopbong'),('정상','Summit'),'badge-summit','1,157m','6.2km',('정상','Summit')),
          (('능선 종주 구간','Ridge run'),('경유','Waypoint'),'badge-shelter','해발 약 900m','14km',('능선','Ridge')),
          (('유명산','Yumyeongsan'),('도착','Finish'),'badge-summit','862m','약 18km',('정상·휴양림 하산','Summit; forest descent'))],
     tips=[('backpack',('준비물','Gear'),('등산화·물 2L 이상·점심·헤드램프.','Boots, 2+ L water, lunch, headlamp.')),
           ('book',('입산','Entry'),('별도 예약 불필요.','No reservation needed.')),
           ('shield',('주의','Cautions'),('장거리 종주 — 기상 악화 시 단축 원칙.','On a long traverse, shorten in bad weather.'))],
     elev='M20 175 C150 150, 280 95, 420 68 S560 80, 660 85 S710 120, 740 130', peak=(420,68), elabel='1,157m',
     mnote='용문-유명 종주', mstart='용문사', mend='유명산',
     mpath='M120 85 C250 115, 370 185, 490 235 S650 310, 700 335', mnodes=[(120,85,10),(490,235,8),(700,335,12)]),
  ]),
 # ── 유명산 (v4) — 표고 정정 862m ──
 'yumyeongsan': dict(ko_name='유명산', en_name='Yumyeongsan', alt='862m', b100=True,
  intro_ko='가평 설악면의 산 862m. 국립 유명산자연휴양림 들머리와 계곡코스, 용문산으로 이어지는 능선이 유명합니다.',
  intro_en='An 862 m peak in Gapyeong\'s Seorak township — the national recreation forest trailhead, a popular valley route, and the ridge that runs on toward Yongmunsan.',
  permit=('휴양림 요금', 'Forest fee'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('휴양림~정상 왕복','Recreation Forest Round Trip'),
     dist=('약 5.5km','~5.5 km'), time=('2~3시간','2–3 h'),
     flow=('유명산자연휴양림','일반 등산로','유명산 862m'),
     desc=('주 등반로 — 휴양림 주차장에서 정상까지 약 2.3~2.4km·1~2시간, 왕복 5.5km 내외.',
          'The main route: 2.3–2.4 km and one to two hours from the forest lot to the summit, about 5.5 km round trip.'),
     segs=[(1,('휴양림 → 등산로 갈림','Forest → junction'),'1km','30분',
            ('휴양림 숲길을 지나 일반/계곡 코스 갈림에 닿는다.','Past the forest paths to the general/valley route split.'),30,'tip',
            ('휴양림 주차 소형 1,500원·입장료 1인 1,000원(동절기 무료).','Forest parking 1,500 won; entry 1,000 won (free in winter).')),
           (2,('등산로 → 정상','Trail → summit'),'1.4km','50~70분',
            ('쉼 없는 오르막이 이어지지만 거리는 짧다.','Relentless but short climbing to the top.'),80,'warn',
            ('체감 난이도는 중간 — 물 휴대.','Feels moderate — carry water.')),
           (3,('정상 → 하산','Summit → descent'),'2.3km','1시간',
            ('온 길로 휴양림에 내려온다.','Return to the forest.'),100,'tip',
            ('계곡코스로 하산 변형도 가능.','A valley-route descent variant is possible.'))],
     cps=[(('휴양림 주차장','Forest lot'),('출발','Trailhead'),'badge-trailhead','해발 약 400m','0km',('주차·화장실·매점','Parking, restrooms, shop')),
          (('등산로 갈림','Junction'),('경유','Waypoint'),'badge-shelter','해발 약 550m','1km',('갈림길','Junction')),
          (('유명산','Yumyeongsan'),('정상','Summit'),'badge-summit','862m','2.4km',('정상','Summit'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1L.','Boots, 1 L water.')),
           ('book',('입산','Entry'),('휴양림 시설 이용·주차 요금은 산림청 안내 확인.','Check Korea Forest Service fees for the forest.')),
           ('shield',('주의','Cautions'),('연속 오르막 — 초보자는 휴식 리듬 필요.','Steady climb — beginners should pace breaks.'))],
     elev='M20 188 C180 165, 330 118, 480 82 S660 50, 740 46', peak=(740,46), elabel='862m',
     mnote='휴양림 코스', mstart='휴양림', mend='정상',
     mpath='M110 340 C240 316, 350 264, 460 208 S620 95, 695 55', mnodes=[(110,340,10),(460,208,8),(695,55,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('계곡코스 왕복','Valley Route Round Trip'),
     dist=('약 6.8km','~6.8 km'), time=('약 3시간','~3 h'),
     flow=('휴양림','계곡코스','유명산 862m'),
     desc=('여름철 인기 계곡코스 — 실측 왕복 최장 6.8km. 계곡 옆 숲길로 오르는 그늘 산행.',
          'The popular summer valley route — up to 6.8 km round trip by tracked logs, climbing in stream-side shade.'),
     segs=[(1,('휴양림 → 계곡길','Forest → valley path'),'2km','1시간',
            ('계곡을 따라 오르는 그늘길.','A shaded climb along the stream.'),40,'tip',
            ('여름 물놀이 산객과 동선 공유.','Shares the path with summer stream visitors.')),
           (2,('계곡길 → 정상','Valley → summit'),'1.4km','1시간',
            ('계곡 끝에서 능선으로 붙어 정상에 오른다.','From the valley head onto the ridge to the top.'),80,'warn',
            ('우천 후 계곡 횡단 수위 주의.','Watch stream crossings after rain.')),
           (3,('정상 → 하산','Summit → descent'),'3.4km','1시간 20분',
            ('일반 등산로로 내려와 휴양림에 복귀한다.','Descend the general route back to the forest.'),100,'tip',
            ('하산 후 계곡 물멱이 마무리.','A stream-side finish.'))],
     cps=[(('휴양림 주차장','Forest lot'),('출발','Trailhead'),'badge-trailhead','해발 약 400m','0km',('주차·화장실','Parking, restrooms')),
          (('계곡길','Valley path'),('경유','Waypoint'),'badge-landmark','해발 약 550m','2km',('계곡','Stream')),
          (('유명산','Yumyeongsan'),('정상','Summit'),'badge-summit','862m','3.4km',('정상','Summit'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1L·여름 수분 대비.','Boots, 1 L water, summer hydration.')),
           ('book',('입산','Entry'),('휴양림 요금 체계는 이용 전 확인.','Check forest fees before you go.')),
           ('shield',('주의','Cautions'),('장마철 계곡 수위 상승 — 대체 동선 준비.','Monsoon streams rise — have a fallback.'))],
     elev='M20 190 C170 168, 320 120, 470 85 S650 50, 740 44', peak=(740,44), elabel='862m',
     mnote='계곡코스', mstart='휴양림', mend='정상',
     mpath='M110 345 C240 320, 350 268, 460 210 S620 95, 695 52', mnodes=[(110,345,10),(460,210,8),(695,52,12)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('유명산~용문산 역종주','Yumyeongsan-Yongmunsan Reverse Traverse'),
     dist=('약 18km','~18 km'), time=('7~8시간','7-8 h'),
     flow=('유명산 휴양림','유명산 862m','능선 종주','가섭봉 1,157m','용문사'),
     desc=('유명산에서 용문산으로 이어지는 18km·7~8시간 종주의 역방향 — 휴양림에서 올라 용문사로 마무리.',
          'The 18 km traverse in reverse: up through the recreation forest, over both summits, finishing at Yongmunsa.'),
     segs=[
       (1, ('휴양림 → 유명산','Forest to Yumyeongsan'), '2.4km', '1시간 30분',
        ('주 등반로로 첫 정상을 밟는다.','Tag the first summit via the main route.'), 25, 'tip',
        ('이른 아침 출발 — 하루 종주.','Early start for a full day.')),
       (2, ('유명산 → 능선 종주','Summit to ridge'), '9.5km', '3시간 30분',
        ('북동 능선을 길게 따라 용문산에 접근한다.','The long northeast ridge toward Yongmunsan.'), 60, 'warn',
        ('중간 하산로 드묾 — 일몰 관리.','Few exits — watch the daylight.')),
       (3, ('능선 → 가섭봉 → 용문사','Ridge to summit to temple'), '6km', '2시간 30분',
        ('가섭봉 1,157m 완등 후 용문사로 하산한다.','Over the 1,157 m summit and down to the temple.'), 100, 'tip',
        ('용문사 관광단지에서 귀가 동선 연결.','Transport connects from the temple lot.')),
     ],
     cps=[
       (('휴양림 주차장','Forest lot'), ('출발','Trailhead'), 'badge-trailhead', '해발 약 400m', '0km', ('주차','Parking')),
       (('유명산','Yumyeongsan'), ('정상','Summit'), 'badge-summit', '862m', '2.4km', ('정상','Summit')),
       (('능선 종주','Ridge'), ('경유','Waypoint'), 'badge-shelter', '해발 약 900m', '11.9km', ('능선','Ridge')),
       (('가섭봉','Gaseopbong'), ('정상','Summit'), 'badge-summit', '1,157m', '17km', ('정상','Summit')),
       (('용문사','Yongmunsa'), ('도착','Finish'), 'badge-landmark', '해발 약 460m', '약 18km', ('사찰·주차','Temple, parking')),
     ],
     tips=[
       ('backpack', ('준비물','Gear'), ('등산화·물 2L 이상·점심·헤드램프.','Boots, 2+ L water, lunch, headlamp.')),
       ('book', ('입산','Entry'), ('휴양림+일반 등산로 — 요금 체계 각각 확인.','Forest fees plus open trails — check both.')),
       ('shield', ('주의','Cautions'), ('양 끝 들머리 상이 — 셔틀 필수.','Different trailheads — shuttle required.')),
     ],
     elev='M20 185 C160 160, 300 118, 440 90 S580 70, 660 45 S710 50, 740 60', peak=(660,45), elabel='1,157m',
     mnote='역종주', mstart='휴양림', mend='용문사',
     mpath='M120 335 C250 300, 370 215, 490 170 S650 70, 700 55', mnodes=[(120,335,10),(490,170,8),(700,55,12)]),
  ]),
 # ── 안산 (v3) — 정체성 정정: 서울 서대문 295.5m 봉수대 ──
 'ansan': dict(ko_name='안산', en_name='Ansan', alt='296m', b100=False,
  intro_ko='서울 서대문구의 낮은 산 295.5m. 정상 봉수대(서울시 기념물 제13호)와 전국 최초 순환형 무장애 안산자락길 7km가 유명합니다.',
  intro_en='A low 295.5 m hill in Seoul\'s Seodaemun district — the beacon station (Seoul Monument No. 13) and Korea\'s first barrier-free 7 km circular jarak-gil.',
  permit=('불필요', 'N/A'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('독립문역~봉수대','Dongnimmun Station–Beacon'),
     dist=('약 2.6km','~2.6 km'), time=('약 1시간','~1 h'),
     flow=('독립문역','안산공원','봉수대 295.5m'),
     desc=('가장 가까운 접근 — 독립문역에서 안산공원을 지나 봉수대까지 약 1.3km 오름.',
          'The closest approach: about 1.3 km up from Dongnimmun Station past Ansan Park to the beacon.'),
     segs=[(1,('독립문역 → 안산공원','Station → park'),'0.5km','10분',
            ('서대문독립공원 방면으로 접어든다.','Toward Seodaemun Independence Park.'),20,'tip',
            ('3호선 독립문역 하차 — 대중교통 최적.','Line 3 Dongnimmun — best transit access.')),
           (2,('안산공원 → 봉수대','Park → beacon'),'1.3km','30~40분',
            ('완만한 숲길로 봉수대에 오른다.','A gentle forest walk to the beacon.'),80,'tip',
            ('정상에서 북한산·인왕산 조망.','Views to Bukhansan and Inwangsan.')),
           (3,('봉수대 → 하산','Beacon → down'),'0.8km','20분',
            ('무악재역 방면으로 내려온다.','Descend toward Mokgyejae Station.'),100,'tip',
            ('무악재역 3호선 환승.','Line 3 connects at Muakjae.'))],
     cps=[(('독립문역','Dongnimmun Stn'),('출발','Trailhead'),'badge-trailhead','해발 약 40m','0km',('지하철','Subway')),
          (('안산공원','Ansan Park'),('경유','Waypoint'),'badge-landmark','해발 약 100m','0.5km',('공원','Park')),
          (('봉수대','Beacon'),('정상','Summit'),'badge-summit','295.5m','1.8km',('서울시 기념물','City monument'))],
     tips=[('backpack',('준비물','Gear'),('운동화·물 — 가벼운 산책.','Sneakers, water — easy.')),
           ('book',('입산','Entry'),('무료·예약 불필요.','Free, no reservation.')),
           ('shield',('주의','Cautions'),('일출 산행객 많은 새벽 혼잡.','Dawn crowds for sunrise.'))],
     elev='M20 200 C220 185, 440 155, 620 125 S710 108, 740 102', peak=(740,102), elabel='295.5m',
     mnote='독립문 코스', mstart='독립문역', mend='봉수대',
     mpath='M110 350 C260 325, 400 265, 520 210 S680 115, 710 102', mnodes=[(110,350,10),(520,210,8),(710,102,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('안산 정상 순환','Ansan Summit Circuit'),
     dist=('약 4.2km','~4.2 km'), time=('약 1시간 40분','~1 h 40 m'),
     flow=('안산공원','봉수대 295.5m','북릉','순환 복귀'),
     desc=('정상을 두르는 순환 코스 — 누적고도 약 230m의 중급 산책.',
          'A circuit over the top — about 230 m of cumulative gain in 1 h 40 m.'),
     segs=[(1,('안산공원 → 봉수대','Park → beacon'),'1.8km','40분',
            ('완만한 오름으로 정상에 오른다.','A gentle climb to the beacon.'),45,'tip',
            ('메타세콰이어 숲길이 아름답다.','The metasequoia grove is lovely.')),
           (2,('봉수대 → 북릉','Beacon → north ridge'),'1.2km','35분',
            ('북릉을 따라 시내 조망을 이어간다.','The north ridge keeps the city views coming.'),75,'tip',
            ('북한산~인왕산 스카이라인.','The Bukhansan–Inwangsan skyline.')),
           (3,('북릉 → 순환 복귀','Ridge → return'),'1.2km','25분',
            ('안산자락길과 연결해 공원으로 복귀한다.','Link the jarak-gil back to the park.'),100,'tip',
            ('자락길 표지를 따르면 길 잃을 염려 없다.','Follow jarak-gil signs — impossible to get lost.'))],
     cps=[(('안산공원','Ansan Park'),('출발','Trailhead'),'badge-trailhead','해발 약 100m','0km',('공원·주차','Park, parking')),
          (('봉수대','Beacon'),('정상','Summit'),'badge-summit','295.5m','1.8km',('기념물','Monument')),
          (('북릉','North ridge'),('경유','Waypoint'),'badge-landmark','해발 약 250m','3km',('조망','Views')),
          (('안산공원','Ansan Park'),('도착','Finish'),'badge-trailhead','해발 약 100m','4.2km',('공원','Park'))],
     tips=[('backpack',('준비물','Gear'),('운동화·물 0.5L.','Sneakers, half a liter.')),
           ('book',('입산','Entry'),('무료.','Free.')),
           ('shield',('주의','Cautions'),('겨울结빙 없는 완만길 — 사계절 가능.','Gentle year-round; little ice.'))],
     elev='M20 200 C200 182, 420 150, 600 122 S700 110, 740 108', peak=(740,108), elabel='295.5m',
     mnote='정상 순환', mstart='안산공원', mend='안산공원',
     mpath='M120 330 C250 305, 370 240, 490 195 S650 110, 690 100 S610 250, 450 290 S230 330, 120 330', mnodes=[(120,330,10),(490,195,8),(690,100,12),(120,330,10)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('안산자락길 완주','Full Jarak-gil Circuit'),
     dist=('약 7km','~7 km'), time=('약 2시간','~2 h'),
     flow=('독립문','봉수대','북릉','무악재','순환 완주'),
     desc=('전국 최초 순환형 무장애 자락길 7km 완주 — 휠체어·유아차 포함 보행 약자도 오를 수 있는 상징 코스.',
          'The full 7 km of Korea first barrier-free circular trail — a symbolic route open to wheelchairs and strollers.'),
     segs=[
       (1, ('독립문 → 봉수대','Dongnimmun to beacon'), '1.8km', '40분',
        ('자락길 표지를 따라 정상으로.','Follow the jarak-gil posts to the top.'), 35, 'tip',
        ('무장애 경사 설계 — 누구나 가능.','Barrier-free grades — open to all.')),
       (2, ('봉수대 → 북릉 → 무악재','Beacon to north ridge to Muakjae'), '3km', '1시간',
        ('북릉 조망길을 지나 무악재로 내려간다.','Down the north ridge to Muakjae.'), 70, 'tip',
        ('서울 시가지 파노라마.','A city panorama.')),
       (3, ('무악재 → 순환 완주','Muakjae to close'), '2.2km', '40분',
        ('서쪽 자락길로 돌아 출발점을 닫는다.','The western leg closes the loop.'), 100, 'tip',
        ('일출·야경 산행 모두 인기.','Popular at dawn and for night views.')),
     ],
     cps=[
       (('독립문','Dongnimmun'), ('출발','Trailhead'), 'badge-trailhead', '해발 약 40m', '0km', ('지하철','Subway')),
       (('봉수대','Beacon'), ('경유','Waypoint'), 'badge-summit', '295.5m', '1.8km', ('기념물','Monument')),
       (('무악재','Muakjae'), ('경유','Waypoint'), 'badge-shelter', '해발 약 70m', '4.8km', ('안부·지하철','Pass; subway')),
       (('독립문','Dongnimmun'), ('도착','Finish'), 'badge-trailhead', '해발 약 40m', '7km', ('순환 완주','Loop done')),
     ],
     tips=[
       ('backpack', ('준비물','Gear'), ('운동화·물.','Sneakers, water.')),
       ('book', ('입산','Entry'), ('무료 — 무장애 시설 안내 활용.','Free; use the accessibility guides.')),
       ('shield', ('주의','Cautions'), ('해질녘 조명 일부 구간 부족 — 랜턴.','Some stretches lack night lighting — bring a light.')),
     ],
     elev='M20 200 C200 185, 430 152, 610 124 S705 108, 740 104', peak=(740,104), elabel='295.5m',
     mnote='자락길 완주', mstart='독립문', mend='독립문',
     mpath='M120 330 C250 305, 380 235, 500 190 S660 105, 700 100 S620 255, 460 295 S230 330, 120 330', mnodes=[(120,330,10),(500,190,8),(700,100,12),(120,330,10)]),
  ]),

})

# ── 생성 루프 ──
import re as _re


def _peak_of(path):
    pts = _re.findall(r'(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)', path)
    pairs = [(float(x), float(y)) for x, y in pts]
    px, py = min(pairs, key=lambda p: p[1])
    return (int(px), int(py))


CONTENT = {}
COURSES = {}

for _mid, d in F7.items():
    for _lang in ('ko', 'en'):
        _ko = _lang == 'ko'
        _ix = 0 if _ko else 1
        L = _lang
        courses = []
        for c in d['courses']:
            flow = list(c['flow'])
            pills = (pill('ruler', '거리' if _ko else 'Distance', c['dist'][_ix]) +
                     pill('clock', '소요' if _ko else 'Time', c['time'][_ix]) +
                     pill('location', '정상' if _ko else 'Summit', d['alt']) +
                     pill_meter('난이도' if _ko else 'Difficulty', c['meter'], 'medium' if c['meter'] <= 3 else 'hard') +
                     pill('star', '100대' if d['b100'] else '명산' if _ko else '100 Mt.' if d['b100'] else 'Mt.', '✓') +
                     pill('book', '허가' if _ko else 'Permit', d['permit'][_ix]))
            courses.append(dict(
                id=c['id'], color=c['color'], hex=c['hexc'], meter=c['meter'],
                level=c['level'][_ix], name=c['name'][_ix], sub=f'{c["dist"][_ix]} · {c["time"][_ix]}',
                tabs=['개요', '경로 안내', '지도', '팁 &amp; 주의'] if _ko else ['Overview', 'Route', 'Map', 'Tips'],
                pills=pills,
                h_flow='코스 흐름' if _ko else 'Course Flow', h_elev='고도 프로파일' if _ko else 'Elevation Profile',
                h_route='구간별 경로 안내' if _ko else 'Route by Section', h_map='코스 개념도' if _ko else 'Concept Map',
                h_cp='체크포인트 표' if _ko else 'Checkpoints',
                flow=flow, elev_label=c['elabel'], elev_path=c['elev'], elev_peak=_peak_of(c['elev']),
                desc=c['desc'][_ix],
                segs=[(no, t[_ix], km, tm, b[_ix], bar, kind, tp[_ix]) for (no, t, km, tm, b, bar, kind, tp) in c['segs']],
                tips=[(ic, t[_ix], [items[_ix]]) for (ic, t, items) in c['tips']],
                cps=[(nm[_ix], bd[_ix], cls, alt, km, am[_ix]) for (nm, bd, cls, alt, km, am) in c['cps']],
                map_note=c['mnote'] if _ko else c['mnote'], map_start=c['mstart'], map_end=c['mend'],
                map_path=c['mpath'], map_nodes=c['mnodes']))
        name = d['ko_name'] if _ko else d['en_name']
        CONTENT.setdefault(_mid, {})[_lang] = dict(
            title=f'{name} 등산 플레이북' if _ko else f'{d["en_name"]} Hiking Playbook',
            meta=(f'{d["ko_name"]}({d["alt"]}). ' + d['intro_ko']) if _ko else (f'Guide to {d["en_name"]} ({d["alt"]}). ' + d['intro_en']),
            h1_card=d['ko_name'] if _ko else d['en_name'],
            p_card=f'{name} · {d["alt"]}' if _ko else f'{d["en_name"]} · {d["alt"]}',
            hero_alt=d['intro_ko'] if _ko else d['intro_en'],
            badge=f'{name} 플레이북' if _ko else f'{d["en_name"]} Playbook',
            h1=f'{name} 등산 플레이북' if _ko else f'{d["en_name"]} Hiking Playbook',
            hero_desc=d['intro_ko'] if _ko else d['intro_en'],
            btn1=d['courses'][0]['name'][_ix], btn2=d['courses'][1]['name'][_ix], btn3=d['courses'][2]['name'][_ix],
            hero_photographer='', hero_url='',
            gal_title=f'{name}의 사계 &amp; 명소' if _ko else f'{d["en_name"]} Seasons',
            lb_zoom='크게 보기' if _ko else 'View larger',
            gallery=[(f'g{i}', f'{name} 풍경 {i}' if _ko else f'{d["en_name"]} scenery {i}', 'Unsplash') for i in range(1, 5)])
        COURSES.setdefault(_mid, {})[_lang] = courses

# ── 크레딧: 기존 v2~v4 크레딧 재사용 (사진 변경 없음) ──
_meta = {}
for _cj in ('k100v2_credits.json', 'k100v3_credits.json', 'k100v4_credits.json'):
    _f = _pl.Path(__file__).parent / _cj
    if _f.exists():
        for _c in _json.load(open(_f)):
            _meta.update(_c)
for _mid, _c in _meta.items():
    if _mid in CONTENT:
        for _lang in ('ko', 'en'):
            CONTENT[_mid][_lang]['hero_photographer'] = _c['hero']['photographer']
            CONTENT[_mid][_lang]['hero_url'] = _c['hero']['url']
            for _i, _g in _c['gallery'].items():
                _cap = f"Photo by &lt;a href='{_g['url']}' target='_blank' rel='noopener'&gt;{_g['photographer']}&lt;/a&gt; on Unsplash"
                _lst = list(CONTENT[_mid][_lang]['gallery'])
                _idx = int(_i[1]) - 1
                if _idx < len(_lst):
                    _lst[_idx] = (_lst[_idx][0], _lst[_idx][1], _cap)
                CONTENT[_mid][_lang]['gallery'] = tuple(_lst)
