F7.update({
 # ── 소금강 (v3) — 정체성 정정: 오대산국립공원 소금강지구, 명승 제1호 ──
 'sogeumgang': dict(ko_name='소금강', en_name='Sogeumgang', alt='1,338m(노인봉)', b100=False,
  intro_ko='오대산국립공원 남서부의 계곡명승 — 대한민국 명승 제1호(1970). 노인봉 1,338m에서 발원한 청학천이 약 13km를 흘러 기암과 층암절벽을 이룹니다.',
  intro_en='A celebrated valley in southwest Odaesan National Park — Korea Scenic Site No. 1 (1970). The Cheonghakcheon stream rises at Noinbong 1,338 m and carves 13 km of crags and cliffs.',
  permit=('불필요', 'N/A'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('소금강계곡~만물상 산책','Valley Walk to Manmulsang'),
     dist=('약 8km','~8 km'), time=('약 4시간','~4 h'),
     flow=('소금강계곡 입구','계곡길','만물상','원점회귀'),
     desc=('소금강계곡을 따라 만물상까지 오가는 대중적 계곡 산책 — 편도 약 4km·왕복 약 4시간으로 안내된다.',
          'The popular valley stroll to the Manmulsang rock figures — about 4 km each way, roughly four hours round trip.'),
     segs=[(1,('계곡 입구 → 계곡길','Valley mouth → gorge path'),'—','40~60분',
            ('계곡 입구에서 청학천을 따라 잘 닦인 길로 들어선다.','Enter on a well-built path along the stream.'),30,'tip',
            ('여름 계곡 산행객과 동선이 겹친다.','Busy with summer stream visitors.')),
           (2,('계곡길 → 만물상','Gorge path → Manmulsang'),'약 4km','1.5~2시간',
            ('기암과 층암절벽을 지나 만물상 바위군에 닿는다.','Past crags and stratified cliffs to the Manmulsang rocks.'),80,'tip',
            ('명승 지정 구역 — 바위 오르기·각화 금지.','Scenic-site zone — no climbing or carving the rocks.')),
           (3,('만물상 → 원점 하산','Manmulsang → return'),'약 4km','1.5시간',
            ('온 계곡길로 되돌아온다.','Return by the same gorge path.'),100,'tip',
            ('우천 후 계곡 접근로 수위를 확인한다.','Check water levels on the access after rain.'))],
     cps=[(('소금강계곡 입구','Valley trailhead'),('출발','Trailhead'),'badge-trailhead','해발 약 300m','0km',('주차·안내','Parking, info')),
          (('청학천 계곡','Cheonghakcheon gorge'),('경유','Waypoint'),'badge-landmark','해발 약 400m','1.5km',('계곡','Gorge')),
          (('만물상','Manmulsang'),('핵심','Highlight'),'badge-landmark','해발 약 600m','약 4km',('기암군','Rock figures'))],
     tips=[('backpack',('준비물','Gear'),('운동화·물·간식 — 계곡 산책 구성.','Sneakers, water, snacks — a valley walk.')),
           ('book',('입산','Entry'),('오대산국립공원 구역 — 공단 탐방 안내를 준수한다.','Odaesan National Park — follow KNPS guidance.')),
           ('shield',('주의','Cautions'),('장마철 계곡 수위 상승 — 우천 시 하류 구간만.','Monsoon streams rise — keep to lower sections in rain.'))],
     elev='M20 195 C180 185, 380 155, 560 120 S700 100, 740 95', peak=(740,95), elabel='약 600m',
     mnote='소금강계곡 산책', mstart='계곡 입구', mend='만물상',
     mpath='M110 350 C260 322, 400 262, 520 205 S680 115, 710 100', mnodes=[(110,350,10),(520,205,8),(710,100,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('진고개~노인봉 왕복','Jingogae–Noinbong Round Trip'),
     dist=('약 8.2km','~8.2 km'), time=('2~3시간','2–3 h'),
     flow=('진고개 탐방지원센터','백두대간 능선','노인봉 1,338m'),
     desc=('노인봉 최단 코스 — 진고개(해발 약 960m)에서 백두대간 능선 약 4km를 따라 노인봉에 오르는 왕복.',
          'The shortest Noinbong route: about 4 km along the Baekdudaegan ridge from Jingogae pass (~960 m) up and back.'),
     segs=[(1,('진고개 → 능선 진입','Jingogae → ridge'),'—','30~40분',
            ('탐방지원센터 뒤 숲길로 백두대간 능선에 붙는다.','Forest behind the center joins the main ridge.'),25,'tip',
            ('진고개 주차장은 주말 만차가 잦다.','The Jingogae lot fills on weekends.')),
           (2,('백두대간 능선 → 노인봉','Ridge → Noinbong'),'약 4km','1.5~2시간',
            ('백두대간 능선을 따라 연속 오르막으로 노인봉 1,338m에 오른다.','A sustained climb along the spine to Noinbong, 1,338 m.'),75,'warn',
            ('능선은 바람에 노출 — 방풍 필수.','Exposed ridge — wind shell essential.')),
           (3,('노인봉 → 진고개 하산','Noinbong → descent'),'약 4.2km','1~1.5시간',
            ('온 능선길로 진고개에 내려온다.','Retrace the ridge to the pass.'),100,'tip',
            ('노인봉에서 두타산·청옥산 방면 전망을 확인하고 하산.','Take in the Duta–Cheongok views before descending.'))],
     cps=[(('진고개 탐방지원센터','Jingogae center'),('출발','Trailhead'),'badge-trailhead','해발 약 960m','0km',('주차·화장실','Parking, restrooms')),
          (('백두대간 능선','Baekdudaegan ridge'),('경유','Waypoint'),'badge-landmark','해발 약 1,150m','1km',('능선','Ridge')),
          (('노인봉','Noinbong'),('정상','Summit'),'badge-summit','1,338m','약 4km',('백두대간 조망','Ridge panorama'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1L·방풍.','Boots, 1 L water, wind shell.')),
           ('book',('입산','Entry'),('국립공원 구역 예약 불필요 — 탐방 안내 준수.','No reservation in the park; follow trail guidance.')),
           ('shield',('주의','Cautions'),('초봄·늦가을 능선 결빙 — 아이젠 대비.','The ridge ices in shoulder seasons — carry crampons.'))],
     elev='M20 180 C180 160, 330 112, 480 78 S660 46, 740 40', peak=(740,40), elabel='1,338m',
     mnote='노인봉 왕복', mstart='진고개', mend='노인봉',
     mpath='M110 340 C240 316, 350 264, 460 208 S620 92, 695 52', mnodes=[(110,340,10),(460,208,8),(695,52,12)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('진고개~노인봉~소금강 종주','Jingogae–Noinbong–Sogeumgang Traverse'),
     dist=('약 13.3km','~13.3 km'), time=('5~7시간','5–7 h'),
     flow=('진고개','노인봉 1,338m','낙영폭포','백운대','소금강계곡'),
     desc=('백두대간 능선을 넘어 소금강계곡으로 하산하는 대표 종주 — 공개 실측 기록 13.3~14.7km·5~7시간.',
          'The signature traverse over the spine and down into the valley — tracked logs run 13.3–14.7 km over 5–7 hours.'),
     segs=[(1,('진고개 → 노인봉','Jingogae → Noinbong'),'약 4km','2시간',
            ('백두대간 능선 오름으로 정상을 먼저 밟는다.','Tag the summit via the ridge climb first.'),30,'warn',
            ('종주 거리 감안 이른 출발.','Early start for the distance.')),
           (2,('노인봉 → 낙영폭포 → 백운대','Noinbong → falls → Baekwandae'),'약 5km','2~3시간',
            ('능선을 내려가 낙영폭포와 백운대 암벽을 지난다.','Down the ridge past the falls and the Baekwandae cliff band.'),65,'warn',
            ('하산 급경사 — 지팡이·장갑 권장.','Steep descent — poles and gloves.')),
           (3,('백운대 → 소금강계곡 하산','Baekwandae → valley exit'),'약 4~5.7km','1.5~2시간',
            ('계곡을 따라 소금강 하류로 빠져 나온다.','Follow the gorge down to the lower valley exit.'),100,'tip',
            ('종주형 동선 — 귀가 교통을 미리 확인한다.','Point-to-point — plan the return transport.'))],
     cps=[(('진고개','Jingogae'),('출발','Trailhead'),'badge-trailhead','해발 약 960m','0km',('주차','Parking')),
          (('노인봉','Noinbong'),('정상','Summit'),'badge-summit','1,338m','약 4km',('조망','Panorama')),
          (('낙영폭포','Nakyeong Falls'),('경유','Waypoint'),'badge-landmark','해발 약 800m','약 7km',('폭포','Falls')),
          (('백운대','Baekwandae'),('경유','Waypoint'),'badge-landmark','해발 약 600m','약 9km',('암벽 전망','Cliff views')),
          (('소금강계곡','Sogeumgang valley'),('도착','Finish'),'badge-trailhead','해발 약 300m','약 13.3km',('계곡·주차','Valley, parking'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 2L·점심·헤드램프.','Boots, 2 L water, lunch, headlamp.')),
           ('book',('입산','Entry'),('국립공원 구역 — 탐방 안내 준수.','Park section — follow KNPS guidance.')),
           ('shield',('주의','Cautions'),('우천 시 계곡 하산로 수위 상승 — 대체 동선 준비.','Gorge exit floods in rain — have a fallback.'))],
     elev='M20 175 C150 155, 280 100, 420 72 S560 95, 660 130 S710 165, 740 175', peak=(420,72), elabel='1,338m',
     mnote='노인봉~소금강 종주', mstart='진고개', mend='소금강계곡',
     mpath='M120 85 C250 115, 370 185, 490 235 S650 310, 700 335', mnodes=[(120,85,10),(490,235,8),(700,335,12)]),
  ]),
 # ── 청태산 (v3) — 정체성 정정: 횡성·평창 1,190m ──
 'cheongtaesan': dict(ko_name='청태산', en_name='Cheongtaesan', alt='1,190m', b100=False,
  intro_ko='횡성 둔내와 평창 방림 경계의 1,190m. 국립청태산자연휴양림의 6개 등산로가 잘 정비되어 둔내 IC에서 차량 15분 거리입니다.',
  intro_en='A 1,190 m mountain on the Hoengseong Dunnae–Pyeongchang Bangrim border, served by six well-built trails of the national recreation forest — 15 minutes from Dunnae IC.',
  permit=('휴양림 요금', 'Forest fee'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('휴양림 최단 코스','Recreation Forest Shortest Route'),
     dist=('—','—'), time=('약 2시간','~2 h'),
     flow=('휴양림 매표소','1휴양관','3등산로','헬기장','정상 1,190m'),
     desc=('매표소에서 1휴양관·3등산로·헬기장을 거쳐 정상까지 오르는 최단 왕복 — 공개 후기 기준 약 2시간.',
          'Up past the first lodge, Trail 3 and the helipad to the summit — about two hours round trip per public logs.'),
     segs=[(1,('매표소 → 1휴양관','Gate → lodge 1'),'—','20~30분',
            ('휴양림 시설 옆 숲길로 시작한다.','A forested start beside the forest facilities.'),20,'tip',
            ('휴양림 주차·시설 이용 요금은 이용 전 확인.','Check forest parking and facility fees first.')),
           (2,('1휴양관 → 헬기장','Lodge → helipad'),'—','50~70분',
            ('3등산로를 따라 숲 능선으로 헬기장 광장에 오른다.','Trail 3 climbs the forested ridge to the helipad clearing.'),60,'tip',
            ('등산로 6개소의 개방 상태는 휴양림 안내를 확인.','Check which of the six trails are open at the office.')),
           (3,('헬기장 → 정상 → 하산','Helipad → summit → down'),'—','50~60분',
            ('마지막 오름으로 정상 1,190m 왕등 후 원점 회귀.','The final pitch to 1,190 m and back down the same way.'),100,'tip',
            ('정상에서 오대산 방면 능선 전망.','Summit views toward the Odaesan ridgelines.'))],
     cps=[(('휴양림 매표소','Forest gate'),('출발','Trailhead'),'badge-trailhead','해발 약 700m','0km',('주차·안내소','Parking, office')),
          (('헬기장','Helipad clearing'),('경유','Waypoint'),'badge-landmark','해발 약 1,050m','—',('광장','Clearing')),
          (('청태산','Cheongtaesan'),('정상','Summit'),'badge-summit','1,190m','—',('전망','Viewpoint'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1L.','Boots, 1 L water.')),
           ('book',('입산','Entry'),('국립자연휴양림 — 산림청(foresttrip) 이용 안내 준수.','National recreation forest — follow Forest Service guidance.')),
           ('shield',('주의','Cautions'),('겨울 결빙·적설 — 아이젠 대비.','Winter ice and snow — carry spikes.'))],
     elev='M20 185 C180 165, 330 118, 480 82 S660 50, 740 44', peak=(740,44), elabel='1,190m',
     mnote='휴양림 최단', mstart='휴양림', mend='정상',
     mpath='M110 340 C240 316, 350 264, 460 208 S620 95, 695 55', mnodes=[(110,340,10),(460,208,8),(695,55,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('등산로 정상 왕복 (장거리 코스)','Longer Trail Round Trip'),
     dist=('—','—'), time=('약 3시간','~3 h'),
     flow=('휴양림 매표소','장거리 등산로','정상 1,190m'),
     desc=('휴양림 6개 등산로 중 긴 축의 코스로 정상을 왕복하는 구성 — 실측 후기 기준 3시간 내외.',
          'A round trip on one of the longer forest trails — about three hours by tracked logs.'),
     segs=[(1,('매표소 → 등산로 진입','Gate → trail entry'),'—','30분',
            ('시설 구간을 지나 등산로에 접어든다.','Past the facilities onto the trail.'),20,'tip',
            ('코스별 난이도·개방 여부는 사전 확인.','Check each trail\'s grade and opening status.')),
           (2,('등산로 → 정상','Trail → summit'),'—','1.5~2시간',
            ('숲 능선을 따라 정상부까지 오른다.','A forested climb to the summit zone.'),75,'warn',
            ('우천 시 뿌리길 미끄럼.','Slippery roots in rain.')),
           (3,('정상 → 하산','Summit → descent'),'—','1~1.5시간',
            ('온 등산로로 휴양림에 내려온다.','Return to the forest by the same trail.'),100,'tip',
            ('하산 후 휴양림 숲해설·숙박 시설 활용 가능.','Forest programs and lodging are available.'))],
     cps=[(('휴양림 매표소','Forest gate'),('출발','Trailhead'),'badge-trailhead','해발 약 700m','0km',('주차·안내소','Parking, office')),
          (('숲 능선','Forest ridge'),('경유','Waypoint'),'badge-shelter','해발 약 950m','—',('숲길','Forest path')),
          (('청태산','Cheongtaesan'),('정상','Summit'),'badge-summit','1,190m','—',('전망','Viewpoint'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1.5L·간식.','Boots, 1.5 L water, snacks.')),
           ('book',('입산','Entry'),('휴양림 요금 체계 — foresttrip.go.kr 확인.','Forest fees — see foresttrip.go.kr.')),
           ('shield',('주의','Cautions'),('봄 자연휴식년제 등 통제 기간 확인.','Check seasonal rest-zone closures in spring.'))],
     elev='M20 188 C170 168, 320 120, 470 84 S650 48, 740 42', peak=(740,42), elabel='1,190m',
     mnote='등산로 왕복', mstart='휴양림', mend='정상',
     mpath='M110 345 C240 320, 350 268, 460 210 S620 95, 695 52', mnodes=[(110,345,10),(460,210,8),(695,52,12)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('3등산로 상행~헬기장 하산 순환','Trail 3 Up, Helipad Down Circuit'),
     dist=('—','—'), time=('약 2.5~3시간','~2.5–3 h'),
     flow=('휴양림 매표소','3등산로','정상 1,190m','헬기장','매표소'),
     desc=('검증된 두 구간을 잇는 순환 구성 — 3등산로로 상행해 정상을 밟고 헬기장 코스로 하산한다.',
          'A loop built from the two verified legs: up Trail 3 to the summit, down via the helipad route.'),
     segs=[(1,('매표소 → 3등산로 → 정상','Gate → Trail 3 → summit'),'—','1.5~2시간',
            ('3등산로를 따라 정상까지 오른다.','Climb Trail 3 to the top.'),55,'tip',
            ('상행은 경사가 완만하다.','The climb is moderate.')),
           (2,('정상 → 헬기장','Summit → helipad'),'—','30~40분',
            ('정상에서 헬기장 광장으로 내려온다.','Descend from the summit to the clearing.'),75,'tip',
            ('갈림길 표지를 따른다 — 이탈 시 등산로 이탈.','Mind the junction signs.')),
           (3,('헬기장 → 1휴양관 → 매표소','Helipad → lodge → gate'),'—','40~50분',
            ('숲길로 매표소에 돌아와 순환을 마친다.','Close the loop back at the gate.'),100,'tip',
            ('순환 구간 조합이라 실거리는 산행 기록 참고.','Distances for the combined loop vary — see trip logs.'))],
     cps=[(('휴양림 매표소','Forest gate'),('출발','Trailhead'),'badge-trailhead','해발 약 700m','0km',('주차','Parking')),
          (('청태산','Cheongtaesan'),('정상','Summit'),'badge-summit','1,190m','—',('전망','Viewpoint')),
          (('헬기장','Helipad clearing'),('경유','Waypoint'),'badge-landmark','해발 약 1,050m','—',('광장','Clearing')),
          (('휴양림 매표소','Forest gate'),('도착','Finish'),'badge-trailhead','해발 약 700m','—',('주차','Parking'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1L·간식.','Boots, 1 L water, snacks.')),
           ('book',('입산','Entry'),('휴양림 이용 안내 준수.','Follow forest guidance.')),
           ('shield',('주의','Cautions'),('갈림길 다수 — 표지 확인 후 진행.','Many junctions — check signs as you go.'))],
     elev='M20 185 C170 168, 320 118, 470 82 S650 60, 730 52 S740 100, 740 130', peak=(740,52), elabel='1,190m',
     mnote='순환', mstart='휴양림', mend='휴양림',
     mpath='M120 330 C250 302, 370 230, 490 180 S650 90, 695 70 S620 250, 460 290 S230 330, 120 330', mnodes=[(120,330,10),(490,180,8),(695,70,12),(120,330,10)]),
  ]),
 # ── 희양산 (v3) — 정체성 정정: 괴산·문경 백두대간 999.1m ──
 'heuiyangsan': dict(ko_name='희양산', en_name='Heuiyangsan', alt='999.1m', b100=True,
  intro_ko='충북 괴산 연풍과 경북 문경 가은에 걸친 백두대간의 화강암 암봉 999.1m. 흑운모 화강암 암릉과 봉암사가 어우러진 산입니다.',
  intro_en='A 999.1 m granite peak of the Baekdudaegan across Goesan Yeonpung and Mungyeong Gaeun, with black-mica granite crags and Bongamsa temple.',
  permit=('불필요', 'N/A'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('은티마을~희양산 왕복','Eunti Village Round Trip'),
     dist=('약 6km','~6 km'), time=('약 3시간','~3 h'),
     flow=('은티마을','지름티재 방면 능선','희양산 999.1m'),
     desc=('가은읍 은티마을에서 지름티재 방면 능선으로 오르는 최단 왕복 — 순환 코스의 상행 구간을 그대로 활용한다.',
          'The shortest out-and-back from Eunti village up the Jieomtijae-direction ridge — the climb half of the circuit.'),
     segs=[(1,('은티마을 → 능선','Eunti → ridge'),'약 1km','30분',
            ('마을 뒤 임도 구간이 완만하게 시작된다.','A gentle forest-road start behind the village.'),20,'tip',
            ('처음 1km는 완만한 임도 구간이다.','The first kilometre is a gentle road stretch.')),
           (2,('능선 → 희양산 정상','Ridge → summit'),'약 2km','1.5시간',
            ('화강암 암봉 능선을 따라 정상 999.1m에 오른다.','Up the granite crags to the 999.1 m summit.'),75,'warn',
            ('암릉 구간 장갑 권장.','Gloves recommended on the crags.')),
           (3,('정상 → 은티 하산','Summit → Eunti descent'),'약 3km','1.5시간',
            ('온 능선길로 마을에 내려온다.','Return the ridge to the village.'),100,'tip',
            ('정상에서 백두대간 능선망 조망.','Summit views along the spine.'))],
     cps=[(('은티마을','Eunti village'),('출발','Trailhead'),'badge-trailhead','해발 약 300m','0km',('마을 주차','Village parking')),
          (('지름티재 방면 능선','Jieomtijae ridge'),('경유','Waypoint'),'badge-landmark','해발 약 650m','1km',('암릉','Crags')),
          (('희양산','Heuiyangsan'),('정상','Summit'),'badge-summit','999.1m','약 3km',('백두대간 조망','Spine views'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·장갑·물 1L.','Boots, gloves, 1 L water.')),
           ('book',('입산','Entry'),('별도 예약·허가 불필요.','No reservation or permit needed.')),
           ('shield',('주의','Cautions'),('화강암 암릉은 우천·결빙 시 매우 미끄럽다.','Granite crags are treacherous wet or icy.'))],
     elev='M20 185 C180 165, 330 115, 480 80 S660 48, 740 42', peak=(740,42), elabel='999.1m',
     mnote='은티 최단', mstart='은티마을', mend='정상',
     mpath='M110 340 C240 316, 350 264, 460 208 S620 95, 695 55', mnodes=[(110,340,10),(460,208,8),(695,55,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('은티마을~지름티재~희양산성 터 순환','Eunti–Jieomtijae Circuit'),
     dist=('약 8.5km','~8.5 km'), time=('약 4시간','~4 h'),
     flow=('은티마을','지름티재','희양산성 터','희양산 999.1m','은티마을'),
     desc=('실측 기록 8.5km·3시간 54분(누적고도 745m)의 순환 코스 — 지름티재와 성터 구간을 거쳐 정상을 두른다.',
          'A tracked 8.5 km loop (3h54m, 745 m of gain) rounding the summit past the pass and old fort wall traces.'),
     segs=[(1,('은티마을 → 지름티재','Eunti → Jieomtijae'),'약 3km','1시간 20분',
            ('임도가 끝나는 지점부터 능선 오름이 본격화된다.','Past the road end the ridge climb begins in earnest.'),35,'warn',
            ('잔돌 많은 구간 — 발 딛기 주의.','Loose rock — mind your footing.')),
           (2,('지름티재 → 성터 구간 → 정상','Pass → wall traces → summit'),'약 2.5km','1시간 20분',
            ('산행 기록에 희양산성 터로 안내되는 능선 구간을 지나 정상에 오른다.','Along the ridge section noted as the fort-wall traces to the top.'),70,'tip',
            ('성터 구간 안내 표지는 변동이 있을 수 있다.','Signage along the wall section may vary.')),
           (3,('정상 → 은티마을 순환 복귀','Summit → return'),'약 3km','1시간 20분',
            ('다른 사면 능선으로 내려와 마을에 돌아온다.','Descend the far flank back to the village.'),100,'tip',
            ('순환 종점부 잔돌 하산 주의.','Careful on the rocky final descent.'))],
     cps=[(('은티마을','Eunti village'),('출발','Trailhead'),'badge-trailhead','해발 약 300m','0km',('마을 주차','Village parking')),
          (('지름티재','Jieomtijae'),('경유','Waypoint'),'badge-shelter','해발 약 700m','약 3km',('안부','Pass')),
          (('성터 구간','Wall traces'),('경유','Waypoint'),'badge-landmark','해발 약 850m','약 5km',('유적 조망','Site views')),
          (('희양산','Heuiyangsan'),('정상','Summit'),'badge-summit','999.1m','약 5.5km',('조망','Panorama')),
          (('은티마을','Eunti village'),('도착','Finish'),'badge-trailhead','해발 약 300m','약 8.5km',('마을 주차','Village parking'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·장갑·물 1.5L.','Boots, gloves, 1.5 L water.')),
           ('book',('입산','Entry'),('별도 예약 불필요.','No reservation needed.')),
           ('shield',('주의','Cautions'),('암릉 연속 구간 — 강풍 시 단축 코스로.','Continuous crags — shorten in strong wind.'))],
     elev='M20 188 C160 168, 310 118, 460 85 S640 52, 730 45 S740 95, 740 125', peak=(730,45), elabel='999.1m',
     mnote='은티 순환', mstart='은티마을', mend='은티마을',
     mpath='M120 330 C250 302, 370 230, 490 180 S650 90, 695 70 S620 250, 460 290 S230 330, 120 330', mnodes=[(120,330,10),(490,180,8),(695,70,12),(120,330,10)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('백두대간 능선 — 이만봉·곰틀봉 연계','Baekdudaegan Link to Immanbong'),
     dist=('약 8~10km','8–10 km'), time=('8~10시간','8–10 h'),
     flow=('은티마을','지름티재','희양산 999.1m','이만봉','곰틀봉'),
     desc=('희양산에서 백두대간 능선을 이만봉·곰틀봉 방면으로 이어가는 장거리 산행 — 공개 안내 기준 8~10시간.',
          'A long ridge day pushing the spine from Heuiyangsan toward Immanbong and Gomteulbong — 8–10 hours per public guides.'),
     segs=[(1,('은티마을 → 희양산','Eunti → summit'),'약 3km','1.5~2시간',
            ('최단 코스로 정상을 먼저 밟는다.','Tag the summit first via the short route.'),25,'warn',
            ('하루 장거리 — 새벽 출발 원칙.','A full day — start at dawn.')),
           (2,('희양산 → 이만봉','Summit → Immanbong'),'약 3~4km','3~4시간',
            ('화강암 암릉이 이어지는 백두대간 본능선 구간.','The spine proper — sustained granite crags.'),60,'warn',
            ('암릉 연속 — 우천·강풍 시 즉시 회귀 판단.','Continuous crags — turn back in wind or rain.')),
           (3,('이만봉 → 곰틀봉 → 하산','Immanbong → Gomteulbong → exit'),'약 2~3km','3~4시간',
            ('늦은 능선 구간을 마치고 하산로로 빠진다.','Finish the ridge and take the exit trail.'),100,'warn',
            ('일몰 전 하산 필수 — 헤드램프 필수품.','Down by dusk — headlamp mandatory.'))],
     cps=[(('은티마을','Eunti village'),('출발','Trailhead'),'badge-trailhead','해발 약 300m','0km',('마을 주차','Village parking')),
          (('희양산','Heuiyangsan'),('정상','Summit'),'badge-summit','999.1m','약 3km',('조망','Panorama')),
          (('이만봉','Immanbong'),('경유','Waypoint'),'badge-summit','해발 약 970m','약 6km',('암릉','Crags')),
          (('곰틀봉','Gomteulbong'),('경유','Waypoint'),'badge-landmark','해발 약 950m','약 8km',('능선','Ridge'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·장갑·물 2L·헤드램프·점심.','Boots, gloves, 2 L water, headlamp, lunch.')),
           ('book',('입산','Entry'),('별도 예약 불필요 — 백두대간 구간 산태 확인.','No permit; check trail conditions on the spine.')),
           ('shield',('주의','Cautions'),('암릉 장거리 — 기상 악화 시 전 구간 회수 원칙.','Long crag day — abandon the whole plan in bad weather.'))],
     elev='M20 180 C150 158, 280 105, 420 75 S560 70, 660 55 S710 90, 740 115', peak=(660,55), elabel='999.1m',
     mnote='백두대간 연계', mstart='은티마을', mend='곰틀봉',
     mpath='M120 340 C250 310, 380 220, 500 170 S660 75, 700 60', mnodes=[(120,340,10),(500,170,8),(700,60,12)]),
  ]),
 # ── 불알산→불암산 (v3) — 정체성 정정: 노원·의정부 507m ──
 'bulsan': dict(ko_name='불암산', en_name='Bulamsan', alt='507m', b100=False,
  intro_ko='서울 노원과 의정부 경계의 507m. 정암사와 거북바위 바위 능선이 특징이며 도봉산·수락산으로 능선이 이어집니다.',
  intro_en='A 507 m hill on the Seoul Nowon–Uijeongbu border — Jeongamsa temple, the Turtle Rock and granite ledges, with the ridge running on to Dobongsan and Suraksan.',
  permit=('불필요', 'N/A'),
  courses=[
   C(id='beginner', color='green', hexc='#6a7d4c', meter=2, level=('초급','Beginner'),
     name=('공영주차장~정암사~정상 원점회귀','Lot–Jeongamsa–Summit Loop'),
     dist=('—','—'), time=('1시간 20분~2시간','1 h 20 m – 2 h'),
     flow=('불암산 공영주차장','정암사','거북바위','정상 507m'),
     desc=('불암산 공영주차장(노원구 덕릉로)에서 정암사·거북바위를 지나 정상에 오르는 최단 원점회귀 — 최단 등정 약 1시간 20분.',
          'From the public lot past Jeongamsa and the Turtle Rock to the summit — the quickest top-out runs about 1h20m.'),
     segs=[(1,('공영주차장 → 정암사','Lot → Jeongamsa'),'—','20~30분',
            ('주차장에서 사찰 경내 등산로로 접어든다.','From the lot into the temple-grounds trailhead.'),25,'tip',
            ('주차장은 주말 오전 만차가 잦다.','The lot fills on weekend mornings.')),
           (2,('정암사 → 거북바위 → 정상','Temple → Turtle Rock → summit'),'—','50~70분',
            ('바위 능선을 따라 거북바위를 지나 정상 507m에 오른다.','Up the granite ledges past the Turtle Rock to 507 m.'),75,'warn',
            ('바위 구간 장갑 권장.','Gloves for the rock steps.')),
           (3,('정상 → 원점 하산','Summit → return'),'—','30~40분',
            ('온 길로 주차장에 내려온다.','Return the same way to the lot.'),100,'tip',
            ('정상에서 도봉산·수락산 능선 조망.','Views over the Dobong–Surak ridgelines.'))],
     cps=[(('불암산 공영주차장','Public lot'),('출발','Trailhead'),'badge-trailhead','해발 약 100m','0km',('주차·화장실','Parking, restrooms')),
          (('정암사','Jeongamsa'),('경유','Waypoint'),'badge-landmark','해발 약 200m','—',('사찰','Temple')),
          (('거북바위','Turtle Rock'),('경유','Waypoint'),'badge-landmark','해발 약 400m','—',('바위','Rock')),
          (('불암산','Bulamsan'),('정상','Summit'),'badge-summit','507m','—',('도봉산 조망','Dobong views'))],
     tips=[('backpack',('준비물','Gear'),('운동화·물 — 가벼운 산행.','Sneakers, water — easy.')),
           ('book',('입산','Entry'),('별도 예약·허가 불필요.','No reservation or permit needed.')),
           ('shield',('주의','Cautions'),('바위 구간은 비 온후 미끄럽다.','The rock steps are slick after rain.'))],
     elev='M20 195 C200 178, 420 140, 600 108 S705 92, 740 88', peak=(740,88), elabel='507m',
     mnote='정암사 최단', mstart='공영주차장', mend='정상',
     mpath='M110 350 C260 322, 400 260, 520 205 S680 110, 710 95', mnodes=[(110,350,10),(520,205,8),(710,95,12)]),
   C(id='intermediate', color='blue', hexc='#456e96', meter=3, level=('중급','Intermediate'),
     name=('송산·국사봉 능선 순환','Songsan–Guksabong Ridge Circuit'),
     dist=('—','—'), time=('약 2시간 30분','~2.5 h'),
     flow=('공영주차장','송산','국사봉','불암산 507m'),
     desc=('불암산 능선의 봉우리들(송산·국사봉)을 경유해 도는 순환 산행 — 실측 후기 기준 약 2시간 30분.',
          'A circuit over the ridge peaks (Songsan, Guksabong) — about 2.5 hours per logged trips.'),
     segs=[(1,('주차장 → 송산','Lot → Songsan'),'—','40~50분',
            ('능선길로 첫 봉우리 송산에 오른다.','Up the ridge to the first peak.'),40,'tip',
            ('갈림길 표지 확인.','Check junction signs.')),
           (2,('송산 → 국사봉','Songsan → Guksabong'),'—','40~50분',
            ('능선 오르내림을 반복하며 국사봉에 닿는다.','Rolling ridge to Guksabong.'),70,'warn',
            ('바위 단차 구간 주의.','Care on the rock steps.')),
           (3,('국사봉 → 불암산 → 하산','Guksabong → summit → down'),'—','50~70분',
            ('정상을 밟고 하산로로 순환을 마친다.','Tag the summit and close the loop on the descent trail.'),100,'tip',
            ('순환 구간 거리는 산행 기록 참고.','Loop distances vary by route — see trip logs.'))],
     cps=[(('공영주차장','Public lot'),('출발','Trailhead'),'badge-trailhead','해발 약 100m','0km',('주차','Parking')),
          (('송산','Songsan'),('경유','Waypoint'),'badge-landmark','해발 약 300m','—',('봉우리','Peak')),
          (('국사봉','Guksabong'),('경유','Waypoint'),'badge-landmark','해발 약 400m','—',('봉우리','Peak')),
          (('불암산','Bulamsan'),('정상','Summit'),'badge-summit','507m','—',('조망','Views'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1L.','Boots, 1 L water.')),
           ('book',('입산','Entry'),('별도 예약 불필요.','No reservation needed.')),
           ('shield',('주의','Cautions'),('능선 갈림길에서 도탈 주의 — 표지 확인.','Mind the ridge junctions.'))],
     elev='M20 192 C190 175, 400 135, 580 105 S700 95, 740 92', peak=(740,92), elabel='507m',
     mnote='능선 순환', mstart='공영주차장', mend='공영주차장',
     mpath='M120 335 C250 308, 370 240, 490 195 S650 110, 690 100 S620 255, 460 295 S230 335, 120 335', mnodes=[(120,335,10),(490,195,8),(690,100,12),(120,335,10)]),
   C(id='advanced', color='red', hexc='#9f5845', meter=4, level=('고급','Advanced'),
     name=('불암산~수락산 종주','Bulamsan–Suraksan Traverse'),
     dist=('—','—'), time=('약 5~6시간','~5–6 h'),
     flow=('불암산 공영주차장','불암산 507m','능선 종주','수락산 638m'),
     desc=('불암산에서 수락산으로 이어지는 능선 종주 — 산악회 공개 안내 기준 5~6시간.',
          'The ridge traverse from Bulamsan on to Suraksan — 5–6 hours per club guides.'),
     segs=[(1,('공영주차장 → 불암산','Lot → Bulamsan'),'—','1~1.5시간',
            ('최단 코스로 첫 정상을 밟는다.','Tag the first summit via the short route.'),20,'tip',
            ('종주 거리 감안 이른 출발.','Early start for the traverse.')),
           (2,('불암산 → 능선 종주','Bulamsan → ridge run'),'—','2.5~3.5시간',
            ('도봉산 서쪽 능선을 따라 수락산 방면으로 길게 이어간다.','The long west-of-Dobong ridgeline toward Suraksan.'),60,'warn',
            ('중간 이탈로 제한 — 체력·수분 관리.','Few exits — manage reserves.')),
           (3,('능선 → 수락산 → 하산','Ridge → Suraksan → exit'),'—','1.5~2시간',
            ('수락산 638m를 밟고 수락역 방면으로 하산한다.','Over Suraksan (638 m) and down toward Surak Station.'),100,'tip',
            ('4호선 수락역에서 귀가.','Line 4 connects at Surak Station.'))],
     cps=[(('불암산 공영주차장','Public lot'),('출발','Trailhead'),'badge-trailhead','해발 약 100m','0km',('주차','Parking')),
          (('불암산','Bulamsan'),('정상','Summit'),'badge-summit','507m','—',('조망','Views')),
          (('능선 종주','Ridge run'),('경유','Waypoint'),'badge-shelter','해발 약 500m','—',('능선','Ridge')),
          (('수락산','Suraksan'),('도착','Finish'),'badge-summit','638m','—',('하산로·지하철','Exit; line 4'))],
     tips=[('backpack',('준비물','Gear'),('트레킹화·물 1.5L·점심·헤드램프.','Boots, 1.5 L water, lunch, headlamp.')),
           ('book',('입산','Entry'),('별도 예약 불필요.','No reservation needed.')),
           ('shield',('주의','Cautions'),('종주형 동선 — 양 끝 교통을 사전 확인.','Point-to-point — check both end transports.'))],
     elev='M20 190 C170 172, 320 135, 470 105 S620 75, 720 55 S740 90, 740 120', peak=(720,55), elabel='638m',
     mnote='불암~수락 종주', mstart='공영주차장', mend='수락산',
     mpath='M120 340 C250 310, 380 230, 500 180 S660 85, 700 65', mnodes=[(120,340,10),(500,180,8),(700,65,12)]),
  ]),
})
